import * as T from 'three';
export const PARTICLE_PRESETS={petals:{size:.045,speed:.35,wind:.2,color:'#ffb8d8',opacity:.65},snow:{size:.018,speed:.18,wind:.08,color:'#e9f4ff',opacity:.8},fireflies:{size:.024,speed:.08,wind:.15,color:'#ffd89a',opacity:.85},sparkles:{size:.027,speed:.15,wind:.12,color:'#d7c6ff',opacity:.6}};
export function particleDefaults(style='petals'){return {enabled:false,style,count:160,width:7,height:5,depth:6,x:0,y:0,z:0,seed:227,...PARTICLE_PRESETS[style]};}
export function particleSeeds(count,seed=227){let n=seed>>>0;return Float32Array.from({length:count*4},()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;});}
export function createParticles(scene){
 const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(new Float32Array(1200*3),3));geometry.setAttribute('particleSeed',new T.BufferAttribute(particleSeeds(1200),4));
 const uniforms={time:{value:0},volume:{value:new T.Vector3(7,5,6)},origin:{value:new T.Vector3()},speed:{value:.35},wind:{value:.2},size:{value:.045},viewportHeight:{value:720},color:{value:new T.Color('#ffb8d8')},opacity:{value:.65},style:{value:0}};
 const material=new T.ShaderMaterial({uniforms,transparent:true,depthWrite:false,toneMapped:false,vertexShader:`attribute vec4 particleSeed;uniform float time,speed,wind,size,viewportHeight;uniform int style;uniform vec3 volume,origin;varying float rotation,phase;void main(){float age=time*speed;vec3 p=vec3((particleSeed.x-.5)*volume.x,mod(particleSeed.y*volume.y-age,volume.y),(particleSeed.z-.5)*volume.z);p.x+=sin(time*.6+particleSeed.w*35.)*wind;p.z+=cos(time*.45+particleSeed.x*24.)*wind*.6;if(style==2){p.y=particleSeed.y*volume.y+sin(time*.7+particleSeed.w*40.)*.25;p.x+=sin(time*.3+particleSeed.z*8.)*.3;}vec4 view=modelViewMatrix*vec4(p+origin,1.);gl_Position=projectionMatrix*view;gl_PointSize=clamp(size*projectionMatrix[1][1]*viewportHeight*.5/max(.1,-view.z),1.,100.);rotation=time*(particleSeed.w+.2)+particleSeed.x*12.;phase=particleSeed.w*20.;}`,
 fragmentShader:`uniform vec3 color;uniform float opacity,time;uniform int style;varying float rotation,phase;void main(){vec2 p=gl_PointCoord-.5;float c=cos(rotation),s=sin(rotation);p=mat2(c,-s,s,c)*p;float alpha;if(style==0){p.y*=1.45;float shape=length(p*vec2(1.+p.y*.4,1.));alpha=1.-smoothstep(.26,.48,shape);}else if(style==3){float star=min(abs(p.x),abs(p.y));alpha=(1.-smoothstep(.015,.06,star))*(1.-smoothstep(.15,.5,length(p)));}else alpha=1.-smoothstep(.08,.5,length(p));if(style==2)alpha*=.55+.45*sin(time*2.+phase);alpha*=opacity;if(alpha<.015)discard;gl_FragColor=vec4(color,alpha);#include <colorspace_fragment>
}`.replace(';#include',';\n#include')});
 const points=new T.Points(geometry,material);points.name='可调舞台粒子';points.frustumCulled=false;points.visible=false;scene.add(points);let lastSeed=227;
 points.onBeforeRender=renderer=>{uniforms.viewportHeight.value=renderer.getDrawingBufferSize(new T.Vector2()).y;};
 return {points,update(time,options={}){const p={...particleDefaults(options.style),...options};points.visible=p.enabled===true;geometry.setDrawRange(0,Math.max(0,Math.min(1200,Math.round(p.count))));if(p.seed!==lastSeed){geometry.attributes.particleSeed.array.set(particleSeeds(1200,p.seed));geometry.attributes.particleSeed.needsUpdate=true;lastSeed=p.seed;}uniforms.time.value=Number.isFinite(time)?time:0;uniforms.volume.value.set(Math.max(.1,p.width),Math.max(.1,p.height),Math.max(.1,p.depth));uniforms.origin.value.set(p.x||0,p.y||0,p.z||0);for(const name of ['speed','wind','size','opacity'])uniforms[name].value=p[name];uniforms.color.value.set(p.color);uniforms.style.value=Math.max(0,Object.keys(PARTICLE_PRESETS).indexOf(p.style));material.blending=p.style==='fireflies'||p.style==='sparkles'?T.AdditiveBlending:T.NormalBlending;},dispose(){points.removeFromParent();geometry.dispose();material.dispose();}};
}
