using System;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.Rendering;
namespace MotionStudio {
 public class NativeClothGPU:MonoBehaviour {
  struct Int4 { public int x,y,z,w; public Int4(BoneWeight b){x=b.boneIndex0;y=b.boneIndex1;z=b.boneIndex2;w=b.boneIndex3;} }
  ComputeShader shader;SkinnedMeshRenderer skin;Dictionary<string,Transform> rig;ComputeBuffer rest,weights,indices,bones,mobility,neighbors,targets,oldTargets,oldPositions,positions,scratch,offsets;bool reset=true;int count;public bool active=true;public float strength=.7f;
  readonly List<ComputeBuffer> buffers=new List<ComputeBuffer>();
  ComputeBuffer Buffer(int n,int stride){var b=new ComputeBuffer(Math.Max(1,n),stride);buffers.Add(b);return b;}
  public void Initialize(SkinnedMeshRenderer renderer,ComputeShader source,Dictionary<string,Transform> skeleton){if(!SystemInfo.supportsComputeShaders){enabled=false;return;}skin=renderer;rig=skeleton;shader=Instantiate(source);var mesh=skin.sharedMesh;count=mesh.vertexCount;rest=Buffer(count,12);rest.SetData(mesh.vertices);weights=Buffer(count,16);indices=Buffer(count,16);bones=Buffer(skin.bones.Length,64);var bw=mesh.boneWeights;weights.SetData(bw.Select(w=>new Vector4(w.weight0,w.weight1,w.weight2,w.weight3)).ToArray());indices.SetData(bw.Select(w=>new Int4(w)).ToArray());var mask=bw.Select(w=>{int[] ids={w.boneIndex0,w.boneIndex1,w.boneIndex2,w.boneIndex3};float[] ws={w.weight0,w.weight1,w.weight2,w.weight3};float total=0;for(int i=0;i<4;i++)if(ids[i]<skin.bones.Length&&(skin.bones[ids[i]].name.StartsWith("Skirt")||skin.bones[ids[i]].name.Contains("Ribbon")))total+=ws[i];return Mathf.Clamp01(total);}).ToArray();mobility=Buffer(count,4);mobility.SetData(mask);var adjacency=Enumerable.Range(0,count).Select(_=>new HashSet<int>()).ToArray();var triangles=mesh.triangles;for(int i=0;i<triangles.Length;i+=3)for(int j=0;j<3;j++){int a=triangles[i+j],b=triangles[i+(j+1)%3];adjacency[a].Add(b);adjacency[b].Add(a);}neighbors=Buffer(count*8,4);neighbors.SetData(adjacency.SelectMany(n=>n.OrderBy(i=>i).Take(8).Concat(Enumerable.Repeat(-1,8)).Take(8)).ToArray());targets=Buffer(count,12);oldTargets=Buffer(count,12);oldPositions=Buffer(count,12);positions=Buffer(count,12);scratch=Buffer(count,12);offsets=Buffer(count,12);positions.SetData(mesh.vertices);foreach(int k in new[]{0,1,2,3}){shader.SetBuffer(k,"Mobility",mobility);shader.SetBuffer(k,"Targets",targets);}shader.SetBuffer(0,"Rest",rest);shader.SetBuffer(0,"Weights",weights);shader.SetBuffer(0,"Indices",indices);shader.SetBuffer(0,"Bones",bones);shader.SetBuffer(1,"PreviousTargets",oldTargets);shader.SetBuffer(1,"PreviousPositions",oldPositions);shader.SetBuffer(2,"Neighbors",neighbors);foreach(var mat in skin.materials){mat.SetBuffer("_GarmentOffsets",offsets);mat.SetFloat("_GPUCloth",1);}shader.SetInt("Count",count);}
  public void ResetState(){reset=true;}
  public bool Validate(){if(offsets==null)return !SystemInfo.supportsComputeShaders;var values=new Vector3[count];offsets.GetData(values);return values.All(v=>!float.IsNaN(v.x)&&!float.IsInfinity(v.x)&&!float.IsNaN(v.y)&&!float.IsInfinity(v.y)&&!float.IsNaN(v.z)&&!float.IsInfinity(v.z));}
  void LateUpdate(){if(shader==null)return;var matrices=skin.bones.Select((b,i)=>b.localToWorldMatrix*skin.sharedMesh.bindposes[i]).ToArray();bones.SetData(matrices);shader.SetInt("Reset",reset?1:0);shader.SetFloat("Dt",Mathf.Clamp(Time.deltaTime,.001f,1f/30));shader.SetFloat("TimeValue",Time.time);shader.SetFloat("Strength",active?strength:0);int groups=(count+63)/64;shader.Dispatch(0,groups,1,1);shader.SetBuffer(1,"Positions",positions);shader.Dispatch(1,groups,1,1);var a=new Vector4[16];var b=new Vector4[16];int used=0;foreach(string side in new[]{"L","R"})foreach(var pair in new[]{new[]{"BodyUpperLeg","BodyLeg",".079"},new[]{"BodyLeg","BodyFoot",".055"},new[]{"BodyFoot","BodyToe",".065"}}){if(!rig.TryGetValue(pair[0]+side,out var x)||!rig.TryGetValue(pair[1]+side,out var y))continue;float r=pair[0]=="BodyUpperLeg"?.079f:pair[0]=="BodyLeg"?.055f:.065f;r*=x.lossyScale.x;a[used]=new Vector4(x.position.x,x.position.y,x.position.z,r);b[used]=new Vector4(y.position.x,y.position.y,y.position.z,r);used++;}shader.SetInt("ColliderCount",used);shader.SetVectorArray("CapsuleA",a);shader.SetVectorArray("CapsuleB",b);for(int i=0;i<6;i++){shader.SetBuffer(2,"InputPositions",positions);shader.SetBuffer(2,"Result",scratch);shader.Dispatch(2,groups,1,1);var temp=positions;positions=scratch;scratch=temp;}shader.SetBuffer(3,"Positions",positions);shader.SetBuffer(3,"Result",offsets);shader.Dispatch(3,groups,1,1);reset=false;}
  void OnDestroy(){foreach(var b in buffers)b.Release();if(shader)Destroy(shader);}
 }
}
