using System;using System.IO;using System.IO.Compression;using System.Linq;using System.Collections.Generic;using Newtonsoft.Json.Linq;using UnityEngine;
namespace MotionStudio {
 public class NativeMotion {
  public JObject doc;Dictionary<string,float[]> buffers=new Dictionary<string,float[]>();public float duration;
  public NativeMotion(string id){doc=NativeAssets.Json("web/game-motions/"+id+".json");foreach(string part in new[]{"body","face"})buffers[part]=Decode(Path.Combine(NativeAssets.Studio,"web/game-motions",(string)doc["files"][part]));duration=(float?)doc["duration"]??(int)doc["parts"]["body"]["frames"]/30f;}
  public static float[] Decode(string path){byte[] input=File.ReadAllBytes(path);using(var stream=new MemoryStream(input,2,input.Length-6))using(var compressed=new DeflateStream(stream,CompressionMode.Decompress))using(var output=new MemoryStream()){compressed.CopyTo(output);var bytes=output.ToArray();var result=new float[bytes.Length/4];Buffer.BlockCopy(bytes,0,result,0,bytes.Length);return result;}}
  public Vector3 InitialPosition(){var part=(JObject)doc["parts"]["body"];var track=part["tracks"].Cast<JObject>().FirstOrDefault(t=>(string)t["name"]=="BodyPelvis"&&(string)t["kind"]=="position");if(track==null)return Vector3.zero;var p=Sample(part,buffers["body"],track,0);return new Vector3(p[0],0,p[2]);}
  public static float[] Sample(JObject part,float[] data,JObject track,float frame){int frames=(int)part["frames"],stride=(int)part["stride"],offset=(int)track["offset"],size=(int)track["size"];frame=Mathf.Clamp(frame,0,frames-1);int a=Mathf.FloorToInt(frame),b=Math.Min(a+1,frames-1);float t=frame-a;float[] value=new float[size];if((string)track["kind"]=="quaternion"){int p=a*stride+offset,q=b*stride+offset;var rotation=Quaternion.Slerp(new Quaternion(data[p],data[p+1],data[p+2],data[p+3]),new Quaternion(data[q],data[q+1],data[q+2],data[q+3]),t);return new[]{rotation.x,rotation.y,rotation.z,rotation.w};}for(int i=0;i<size;i++)value[i]=Mathf.Lerp(data[a*stride+offset+i],data[b*stride+offset+i],t);return value;}
  public void Apply(NativeActor actor,float frame){actor.root.localPosition=Vector3.zero;foreach(string family in new[]{"body","face"}){var part=(JObject)doc["parts"][family];var nodes=actor.partBones[family];foreach(JObject track in part["tracks"]){string kind=(string)track["kind"],name=(string)track["name"];float[] value=Sample(part,buffers[family],track,frame);if(kind=="morph"){foreach(var mesh in actor.meshes)for(int i=0;i<mesh.sharedMesh.blendShapeCount;i++)if(name==mesh.sharedMesh.GetBlendShapeName(i)||name.EndsWith("."+mesh.sharedMesh.GetBlendShapeName(i)))mesh.SetBlendShapeWeight(i,value[0]);continue;}if(!nodes.TryGetValue(name,out var bone))continue;if(kind=="quaternion")bone.localRotation=new Quaternion(value[0],value[1],value[2],value[3]);if(kind=="euler")bone.localRotation=Quaternion.Euler(value[0],value[1],value[2]);if(kind=="position"){bone.localPosition=new Vector3(value[0],value[1],value[2]);if(name=="BodyPelvis"){var start=Sample(part,buffers[family],track,0);var p=bone.localPosition;p.x=(p.x-start[0])/actor.bodyScale;p.z=(p.z-start[2])/actor.bodyScale;bone.localPosition=p;}}if(kind=="scale"&&part["rest"]?[name]?["scale"]!=null){var scale=part["rest"][name]["scale"];bone.localScale=new Vector3(value[0]/Mathf.Max(.0001f,(float)scale[0]),value[1]/Mathf.Max(.0001f,(float)scale[1]),value[2]/Mathf.Max(.0001f,(float)scale[2]));}}}
   if(actor.bones.TryGetValue("BodyPelvis",out var hip)){var p=hip.localPosition;actor.root.localPosition=new Vector3(p.x*actor.bodyScale,0,p.z*actor.bodyScale);hip.localPosition=new Vector3(0,p.y,0);}actor.Attachments();
  }
 }
 public class NativeCamera {
  JObject doc;float[] data;Transform[] nodes;Transform root;public NativeCamera(string song){doc=NativeAssets.Json("web/game-cameras/"+song+".json");data=NativeMotion.Decode(Path.Combine(NativeAssets.Studio,"web/game-cameras",(string)doc["file"]));root=new GameObject("Authored cameras").transform;nodes=NativeAssets.Nodes((JArray)doc["nodes"],root);}
  public void Apply(Camera camera,float frame,NativeActor[] actors,int[] sourceSlots){var latch=doc["tracks"].Cast<JObject>().FirstOrDefault(t=>(string)doc["nodes"][(int)t["node"]]["name"]=="Latch"&&(string)t["kind"]=="position");if(latch!=null){int f=Mathf.Clamp(Mathf.FloorToInt(frame),0,(int)doc["frames"]-1);while(f>0&&NativeMotion.Sample(doc,data,latch,f)[0]<-1e-5)f--;if(f<Mathf.FloorToInt(frame))frame=f;}
   float focal=(float)doc["lens"]["focalLength"];foreach(JObject track in doc["tracks"]){float[] v=NativeMotion.Sample(doc,data,track,frame);var node=nodes[(int)track["node"]];string kind=(string)track["kind"];if(kind=="position")node.localPosition=new Vector3(v[0],v[1],v[2]);if(kind=="quaternion")node.localRotation=new Quaternion(v[0],v[1],v[2],v[3]);if(kind=="euler")node.localRotation=Quaternion.Euler(v[0],v[1],v[2]);if(kind=="scale")node.localScale=new Vector3(v[0],v[1],v[2]);if(kind=="focalLength")focal=v[0];}
   float height=0;int count=0;for(int i=0;i<5;i++)if(actors[i]!=null){string name="Ch0"+sourceSlots[i];var flag=doc["tracks"].Cast<JObject>().FirstOrDefault(t=>(string)doc["nodes"][(int)t["node"]]["name"]==name&&(string)t["kind"]=="position");if(flag!=null&&NativeMotion.Sample(doc,data,flag,frame)[0]<-1e-5){height+=actors[i].bodyScale;count++;}}var target=nodes[(int)doc["cameraNode"]];camera.transform.SetPositionAndRotation(target.position*(count>0?height/count:1),target.rotation);var lens=doc["lens"];camera.usePhysicalProperties=true;camera.sensorSize=new Vector2((float?)lens["sensorWidth"]??36,(float?)lens["sensorHeight"]??24);camera.gateFit=(Camera.GateFitMode)((int?)lens["gateFit"]??1);camera.focalLength=focal;camera.nearClipPlane=(float?)lens["near"]??.01f;camera.farClipPlane=(float?)lens["far"]??200;camera.orthographic=(bool?)lens["orthographic"]??false;camera.orthographicSize=(float?)lens["orthographicSize"]??2;}
  public void Dispose(){UnityEngine.Object.Destroy(root.gameObject);}
 }
}
