import {readFile,writeFile,mkdir,copyFile,stat,realpath,unlink} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {spawn} from 'node:child_process';
import {safeUpdateTarget} from './github-update.mjs';
const root=await realpath(path.dirname(path.dirname(fileURLToPath(import.meta.url)))),[token,oldPid]=process.argv.slice(2);
if(!/^[a-f0-9-]{36}$/.test(token||'')||!/^\d+$/.test(oldPid||''))throw new Error('更新参数无效');const directory=path.join(root,'cache/updates',token),plan=JSON.parse(await readFile(path.join(directory,'plan.json'),'utf8'));
async function restart(){const portable=await stat(path.join(root,'runtime/node/node.exe')).then(()=>true).catch(()=>false),script=path.join(root,'tools',portable?'portable-service.ps1':'start-studio.ps1');const child=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',script,'-NoBrowser'],{cwd:root,windowsHide:true,detached:true,stdio:'ignore'});child.unref();}
try{const start=Date.now();while(true){let alive=true;try{process.kill(Number(oldPid),0);}catch{alive=false;}if(!alive)break;if(Date.now()-start>30000)throw new Error('旧服务尚未退出，未修改文件');await new Promise(r=>setTimeout(r,250));}
 if(plan.token!==token||!Array.isArray(plan.files))throw new Error('更新计划无效');for(const file of plan.files){await safeUpdateTarget(root,file.name);const source=path.join(directory,'source',file.name),bytes=await readFile(source);if(createHash('sha256').update(bytes).digest('hex')!==file.sha256)throw new Error('更新文件校验失败：'+file.name);}
 const backups=[];try{for(const file of plan.files){const target=await safeUpdateTarget(root,file.name),backup=path.join(directory,'backup',file.name);let existed=false;try{await stat(target);existed=true;await mkdir(path.dirname(backup),{recursive:true});await copyFile(target,backup);}catch(e){if(e.code!=='ENOENT')throw e;}backups.push({name:file.name,existed});await mkdir(path.dirname(target),{recursive:true});await copyFile(path.join(directory,'source',file.name),target);}}catch(e){for(const file of backups.reverse())if(file.existed)await copyFile(path.join(directory,'backup',file.name),await safeUpdateTarget(root,file.name));else await unlink(await safeUpdateTarget(root,file.name)).catch(e=>{if(e.code!=='ENOENT')throw e;});throw e;}
 await writeFile(path.join(directory,'result.json'),JSON.stringify({success:true,version:plan.version}));await restart();
}catch(e){await writeFile(path.join(directory,'result.json'),JSON.stringify({success:false,error:e.message}));await restart();process.exitCode=1;}
