import {readFile,mkdir,writeFile,realpath,lstat} from 'node:fs/promises';
import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {unzipSync} from 'fflate';
export const UPDATE_REPO='Sora-Ayano/227-Motion-Studio';
const api='https://api.github.com/repos/'+UPDATE_REPO;
export function newerVersion(remote,local){const parse=v=>/^v?(\d+)\.(\d+)\.(\d+)$/.exec(v||'')?.slice(1).map(Number),a=parse(remote),b=parse(local);if(!a||!b)return false;for(let i=0;i<3;i++)if(a[i]!==b[i])return a[i]>b[i];return false;}
const headers={'User-Agent':'227-Motion-Studio-Updater','Accept':'application/vnd.github+json'};
export async function checkGitHubUpdate(current,request=fetch){const response=await request(api+'/releases/latest',{headers,signal:AbortSignal.timeout(15000)});if(response.status===404)return {current,available:false,message:'GitHub 尚未发布正式 Release',repository:'https://github.com/'+UPDATE_REPO+'/releases'};if(!response.ok)throw new Error('GitHub 更新检查失败（HTTP '+response.status+'）');const release=await response.json(),version=release.tag_name;
 return {current,version,available:!release.draft&&!release.prerelease&&newerVersion(version,current),message:newerVersion(version,current)?'有可用更新':'当前版本已是最新，或比公开版更新',repository:'https://github.com/'+UPDATE_REPO+'/releases',releaseURL:'https://github.com/'+UPDATE_REPO+'/releases/tag/'+encodeURIComponent(version),archiveURL:api+'/zipball/'+encodeURIComponent(version)};
}
export function allowedUpdatePath(name){return /^(?:server\.mjs|package(?:-lock)?\.json|config\.example\.json|README\.md|LICENSE|NOTICE|THIRD_PARTY_NOTICES\.md|requirements\.txt)$/.test(name)||/^web\/(?:core|lib|unity-package)\/[^:]+\.(?:mjs|js|cs|shader|txt|md)$/.test(name)||/^web\/[^/]+\.(?:mjs|html|css|svg|png)$/.test(name)||/^web\/models\/(?:manifest\.json|(?:pose_landmarker_(?:heavy|full)|face_landmarker|hand_landmarker)\.task|LICENSE(?:\.txt)?|[^/]+\.md)$/.test(name)||/^(?:unity|docs|licenses)\/[^:]+\.(?:cs|md|txt)$/.test(name)||/^tools\/[^/]+\.(?:mjs|py|ps1)$/.test(name);}
export function unpackSourceUpdate(bytes){let expanded=0;const all=unzipSync(bytes,{filter:file=>{expanded+=file.originalSize;if(file.originalSize>128*1024*1024||expanded>256*1024*1024)throw new Error('更新包解压体积异常');return true;}}),files={};let prefix=null;
 for(const [name,data] of Object.entries(all)){if(name.endsWith('/'))continue;if(name.includes('\\')||name.includes(':')||name.split('/').some(p=>p==='..'||p==='.'||!p))throw new Error('更新包包含不安全路径');const parts=name.split('/');if(parts.length<2)throw new Error('更新包目录格式不正确');prefix??=parts[0];if(parts[0]!==prefix)throw new Error('更新包目录不一致');const relative=parts.slice(1).join('/');if(allowedUpdatePath(relative))files[relative]=data;}
 const packageJSON=files['package.json'];if(!packageJSON||!files['server.mjs']||!files['web/app.mjs'])throw new Error('更新包缺少编辑器源码');const metadata=JSON.parse(new TextDecoder().decode(packageJSON));if(metadata.name!=='227-motion-studio')throw new Error('更新包属于其他项目');return {files,metadata};
}
export async function safeUpdateTarget(root,relative){if(!allowedUpdatePath(relative)||relative.includes('\\')||relative.split('/').some(p=>p==='..'||p==='.'||!p))throw new Error('更新文件不在允许范围');const target=path.resolve(root,relative);if(!target.startsWith(root+path.sep))throw new Error('更新文件超出项目目录');let parent=path.dirname(target);while(parent!==root){try{if((await lstat(parent)).isSymbolicLink())throw new Error('更新目录不能是符号链接');}catch(e){if(e.code!=='ENOENT')throw e;}parent=path.dirname(parent);}try{if((await lstat(target)).isSymbolicLink())throw new Error('更新目标不能是符号链接');}catch(e){if(e.code!=='ENOENT')throw e;}return target;}
export async function prepareGitHubUpdate(root,current){const update=await checkGitHubUpdate(current);if(!update.available)throw new Error(update.message);const response=await fetch(update.archiveURL,{headers,signal:AbortSignal.timeout(120000)});if(!response.ok)throw new Error('更新包下载失败');const chunks=[];let size=0;for await(const chunk of response.body){size+=chunk.length;if(size>96*1024*1024)throw new Error('源码更新包过大');chunks.push(chunk);}const bytes=Buffer.concat(chunks),{files,metadata}=unpackSourceUpdate(bytes),old=JSON.parse(await readFile(path.join(root,'package.json'),'utf8'));if(!newerVersion(metadata.version,current)||metadata.version!==update.version.replace(/^v/,''))throw new Error('源码版本与 Release 不一致');if(JSON.stringify(Object.entries(metadata.dependencies||{}).sort())!==JSON.stringify(Object.entries(old.dependencies||{}).sort()))throw new Error('新版本需要不同运行依赖，请下载新的完整一键包');root=await realpath(root);const token=randomUUID(),directory=path.join(root,'cache/updates',token);await mkdir(directory,{recursive:true});const entries=[];
 for(const [name,bytes] of Object.entries(files)){await safeUpdateTarget(root,name);const file=path.join(directory,'source',name);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,bytes);entries.push({name,sha256:createHash('sha256').update(bytes).digest('hex')});}
 await writeFile(path.join(directory,'plan.json'),JSON.stringify({token,version:metadata.version,files:entries}));return {token,version:metadata.version,files:entries.length,message:'源码更新已下载；应用时自动备份旧版本，保留模型、资源与个人工程'};
}
