import {exportFrameVideo} from './core/frame-export.mjs';
import {roleSlot} from './core/game-layout.mjs';
import {VIDEO_SIZES,videoSize,frameRect} from './core/video-output.mjs';
import {renderPreset} from './core/filters.mjs';
import {postLocal} from './core/local-api.mjs';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import { OutlineEffect } from 'three/addons/effects/OutlineEffect.js';
import { createCharacter } from './core/model.mjs';
import { captureRest, resetBones, Retargeter, MAPPING, MORPH_MAPPING, validateProject } from './core/retarget.mjs';
import { parseVMD, emptyClip, sampleCamera, writeVMD, linearInterpolation, bracket } from './core/vmd.mjs';
import { initFeatures,resolveExtraModel,updateExtraUI,storeFiles,getFiles } from './features.mjs';
import { MMD_PARENT } from './core/rig.mjs';
import { toUnityAnimation } from './core/unity-export.mjs';
import { previewLight } from './core/materials.mjs';
import { restoreClothGeometry } from './core/cloth.mjs';
import {loadGameMotion} from './core/game-motion.mjs';
import {localizeCatalog,zh} from './core/i18n.mjs';
import {initSceneTools} from './scene-tools.mjs';
import {AudioTimeline} from './core/audio-timeline.mjs';
import {initTrackEditor} from './track-editor.mjs';
import {createFilters} from './core/filters.mjs';
import {initAppearance} from './scene-appearance.mjs';
import {fitDistance} from './core/camera.mjs';
import {initCustomAccessories} from './custom-accessories.mjs';
import {exportUnityModelPackage} from './core/unity-model-export.mjs';
import {saveOutput} from './save-output.mjs';
const $=id=>document.getElementById(id);
const state={catalog:null,model:null,retarget:null,components:{body:'120010100',face:'21010000',hair:'11010000',skin:'30000000',accessory:'',faceAccessory:'',backAccessory:''},profile:null,
 materialOverrides:{},variants:{body:'01',accessory:'01',subwear:'01'},motion:emptyClip(),edits:{bones:{},morphs:{}},frame:0,duration:300,playing:false,loop:true,speed:1,selection:null,dirty:true,unsaved:false,history:[],future:[],loadGeneration:0,recording:false,outputFPS:60,videoResolution:"1920x1080"};
let customAccessories,sceneTools,audioTrack,featureController,trackEditor,filters,appearance,renderer,effect,scene,camera,controls,grid,ground,keyLight,skeletons=[],lastTick=performance.now(),lastInspector=0,autosaveTimer,toastTimer,audioURL,audioContext,audioNode,audioDestination,recorder;
const audio=new Audio();audio.preload='auto';
const canvas=$('viewportCanvas');
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),5000);}
function status(text){$('status').textContent=text;}
function setLoading(loading,text){if(state.restoring&&!loading)return;$('loading').classList.toggle('hidden',!loading);if(text)$('loading').querySelector('strong').textContent=text;}
function fail(e){console.error(e);toast(e.message||String(e));status('操作失败：'+(e.message||e));}
let lastExportURL;
function showExport(saved,name){let a=$('lastExport');if(!a){a=document.createElement('a');a.id='lastExport';document.querySelector('.statusbar').append(a);}a.href=saved.url;a.download=name;a.textContent='下载：'+name;a.title='已保存：'+(saved.path||saved.name);if(name.endsWith('.mp4')){let dialog=$('videoExportPreview');if(!dialog){dialog=document.createElement('dialog');dialog.id='videoExportPreview';dialog.innerHTML='<div class="section-head"><h2>MP4 导出完成</h2><button id="closeVideoPreview">关闭</button></div><video id="exportedVideo" controls preload="metadata"></video><p class="hint">文件已保存至选定位置，可在这里检查画面与音频。</p>';document.body.append(dialog);$('closeVideoPreview').onclick=()=>{$('exportedVideo').pause();dialog.close();};}$('exportedVideo').src=saved.url;dialog.showModal();}}
function updateLight(){const azimuth=Number($('lightAzimuth').value)*Math.PI/180,elevation=Number($('lightElevation').value)*Math.PI/180;previewLight.direction.value.set(Math.sin(azimuth)*Math.cos(elevation),Math.sin(elevation),-Math.cos(azimuth)*Math.cos(elevation));keyLight.position.copy(previewLight.direction.value).multiplyScalar(5).add(keyLight.target.position);}
async function download(data,name,type='application/octet-stream'){try{const saved=await saveOutput(data,name,type);if(saved){showExport(saved,name);status('已保存：'+(saved.path||saved.name));}return saved;}catch(e){fail(e);return null;}}
function project(){return {...sceneTools?.save(),audioOffset:audioTrack?.offset||0,format:'nananiji-studio',version:1,renderVersion:7,autoGameStage:state.autoGameStage!==false,videoResolution:state.videoResolution,videoEncoder:$('videoEncoder').value,videoPipeline:Number($('videoPipeline').value),timelineZoom:Number($('timelineZoom').value),filter:state.filter||'original',filterStrength:state.filterStrength??1,greenScreen:!!state.greenScreen,rendering:state.rendering||{},backgroundFit:state.backgroundFit||'contain',lighting:state.lighting||{},sceneCollapsed:state.sceneCollapsed||{},customAccessories:state.customAccessories||[],backgroundLibrary:state.backgroundLibrary||[],name:$('projectName').textContent,components:{...state.components},variants:state.variants,materialOverrides:state.materialOverrides,background:state.background,audioId:$('audioLibrary')?.value,profile:state.profile,motion:state.motion,edits:state.edits,duration:state.duration,outputFPS:state.outputFPS,mp4IncludeAudio:$('mp4IncludeAudio').checked,previewQuality:state.previewQuality||'smooth',audioFile:state.audioFile,backgroundImage:state.backgroundImage,retarget:{settings:state.retarget?.settings,mapping:state.retarget?.mapping,sourcePositions:state.retarget?.sourcePositions},scene:{background:$('backgroundColor').value,outline:$('enableOutline').checked,shadow:$('enableShadow').checked,cameraMotion:$('enableCamera').checked,camera:{position:camera.position.toArray(),target:controls.target.toArray(),fov:camera.fov},light:keyLight.intensity,lightAzimuth:Number($('lightAzimuth').value),lightElevation:Number($('lightElevation').value)},audioName:$('audioName').textContent};}
function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('nananiji-studio',1);request.onupgradeneeded=()=>request.result.createObjectStore('projects');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function saveLocal(){if(!state.model||state.restoring)return;try{const db=await openDB(),tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(project(),'autosave');await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error);});db.close();$('saveStatus').textContent='已自动保存 · 本机';}catch{$('saveStatus').textContent='自动保存不可用，请保存工程文件';}}
async function readLocal(){try{const db=await openDB();const p=await new Promise((r,j)=>{const q=db.transaction('projects').objectStore('projects').get('autosave');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});db.close();return p;}catch{return null;}}
function changed(){state.dirty=true;if(state.restoring)return;state.unsaved=true;$('saveStatus').textContent='正在自动保存…';clearTimeout(autosaveTimer);autosaveTimer=setTimeout(saveLocal,800);}
function snapshot(){return {edits:structuredClone(state.edits),duration:state.duration,motion:structuredClone(state.motion),cameraTrack:structuredClone(state.cameraTrack),actorEdits:sceneTools?.ensemble.actors.map(a=>({id:a.config.id,edits:structuredClone(a.config.edits)}))};}
function pushHistory(){state.history.push(snapshot());if(state.history.length>80)state.history.shift();state.future=[];updateHistory();}
function restore(snapshot){sceneTools?.setTrack(snapshot.cameraTrack||null);for(const saved of snapshot.actorEdits||[]){const actor=sceneTools.ensemble.actors.find(a=>a.config.id===saved.id);if(actor)actor.config.edits=saved.edits;}state.edits=snapshot.edits;state.motion=snapshot.motion||state.motion;state.duration=snapshot.duration;refreshMotion();$('durationInput').value=state.duration;changed();drawTimeline();}
function updateHistory(){$('undo').disabled=!state.history.length;$('redo').disabled=!state.future.length;}
function undo(){if(!state.history.length)return;state.future.push(snapshot());restore(state.history.pop());updateHistory();}
function redo(){if(!state.future.length)return;state.history.push(snapshot());restore(state.future.pop());updateHistory();}
function apply(){if(!state.model)return;state.retarget.apply(state.motion,state.frame,state.edits);featureController?.updateScene(state.frame/30);sceneTools?.update();state.dirty=false;}
function viewCamera(){return sceneTools?.renderCamera()||camera;}
function fitBackground(root){togglePlay(false);state.previewCamera=false;const box=new THREE.Box3().setFromObject(root).union(sceneTools.ensemble.bounds()),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());camera.fov=35;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(0,0,-fitDistance(size,camera.aspect,camera.fov)));camera.far=Math.max(200,size.length()*5);controls.maxDistance=Math.max(80,size.length()*5);camera.updateProjectionMatrix();controls.update();changed();}
function renderScene(outline=false){previewLight.ambient.value=state.lighting?.ambient??.16;previewLight.softness.value=state.lighting?.softness??.35;if(state.rendering?.autoFocus&&state.model?.head){const active=viewCamera();active.updateMatrixWorld(true);state.rendering.focus=Math.max(.1,-active.worldToLocal(state.model.head.getWorldPosition(new THREE.Vector3())).z);}previewLight.rim.value=state.rendering?.enabled?state.rendering.rim??.07:0;filters.render(()=>drawScene(outline),state.filter,state.filterStrength,state.greenScreen,state.rendering,viewCamera());}
function setPreviewQuality(){if(!renderer)return;const high=state.previewQuality==='high';renderer.setPixelRatio(Math.min(devicePixelRatio,high?2:1));keyLight.shadow.mapSize.set(high?2048:1024,high?2048:1024);keyLight.shadow.map?.dispose();keyLight.shadow.map=null;state.drawPending=true;}
function drawScene(outline=false){const c=viewCamera(),target=renderer.getRenderTarget(),size=target?new THREE.Vector2(target.width,target.height).divideScalar(renderer.getPixelRatio()):renderer.getSize(new THREE.Vector2()),aspect=state.cameraViewAspect;renderer.setScissorTest(false);renderer.setViewport(0,0,size.x,size.y);renderer.autoClear=true;if(aspect){const old=scene.background;scene.background=null;renderer.setClearColor(state.greenScreen?'#00ff00':'#171922');renderer.clear();scene.background=old;const width=Math.min(size.x,size.y*aspect),height=width/aspect,x=(size.x-width)/2,y=(size.y-height)/2;renderer.setViewport(x,y,width,height);renderer.setScissor(x,y,width,height);renderer.setScissorTest(true);}if(state.background&&!state.background.occlusion&&!state.greenScreen){c.layers.set(1);renderer.render(scene,c);renderer.autoClear=false;renderer.clearDepth();const backdrop=scene.background;scene.background=null;c.layers.set(0);renderer.render(scene,c);if(outline)effect.renderOutline(scene,c);scene.background=backdrop;renderer.autoClear=true;}else {c.layers.set(0);renderer.render(scene,c);if(outline)effect.renderOutline(scene,c);}renderer.setScissorTest(false);renderer.setViewport(0,0,size.x,size.y);}
function setFrame(frame,syncAudio=true){state.frame=Math.max(0,Math.min(state.duration,Number(frame)||0));state.dirty=true;$('frameInput').value=Math.round(state.frame);const sec=state.frame/30;$('timeDisplay').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${(sec%60).toFixed(2).padStart(5,'0')}`;
 const scroll=$('timelineScroll'),x=20+state.frame*timelineScale();if(!state.scrubbing&&(x<scroll.scrollLeft||x>scroll.scrollLeft+scroll.clientWidth-25))scroll.scrollLeft=Math.max(0,x-scroll.clientWidth*.25);
 if(syncAudio&&audioURL)audioTrack?.seek(sec,state.playing);audioTrack?.display(sec);drawTimeline();}
async function togglePlay(force){state.dirty=true;state.playing=force??!state.playing;if(state.playing&&state.frame>=state.duration)setFrame(0);$('play').textContent=state.playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',state.playing?'暂停':'播放');lastTick=performance.now();
 if(audioURL){audio.playbackRate=state.speed;if(state.playing){audioTrack?.seek(state.frame/30,true);try{if(audioTrack?.isWithin(state.frame/30))await audio.play();}catch(e){toast('音频尚未就绪，已继续播放动画');}}else audio.pause();}}
function initRenderer(){
 renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;filters=createFilters(renderer);
 effect=new OutlineEffect(renderer,{defaultThickness:.0018,defaultColor:[.08,.06,.13],defaultAlpha:.8});scene=new THREE.Scene();scene.background=new THREE.Color('#262937');scene.add(new THREE.HemisphereLight(0xf3efff,0x9ba4bb,1.15));
 keyLight=new THREE.DirectionalLight(0xffffff,1);keyLight.position.set(-2,4,-3);keyLight.castShadow=true;keyLight.shadow.mapSize.set(2048,2048);keyLight.shadow.camera.left=-2;keyLight.shadow.camera.right=2;keyLight.shadow.camera.top=2;keyLight.shadow.camera.bottom=-2;keyLight.shadow.camera.near=.1;keyLight.shadow.camera.far=12;keyLight.shadow.radius=2;keyLight.shadow.bias=-.0001;keyLight.shadow.normalBias=.008;keyLight.target.position.set(0,.8,0);scene.add(keyLight,keyLight.target);updateLight();
 const rim=new THREE.DirectionalLight(0xa0a9ff,.45);rim.position.set(2,2,1);scene.add(rim);
 ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.25}));ground.rotation.x=-Math.PI/2;ground.position.y=-.002;ground.receiveShadow=true;scene.add(ground);
 grid=new THREE.GridHelper(12,60,0x66647a,0x414454);grid.material.transparent=true;grid.material.opacity=.45;scene.add(grid);
 camera=new THREE.PerspectiveCamera(35,1,.01,200);camera.position.set(0,1,-3.6);controls=new OrbitControls(camera,canvas);controls.target.set(0,.85,0);controls.enableDamping=true;controls.dampingFactor=.12;controls.minDistance=.3;controls.maxDistance=80;controls.update();
 controls.addEventListener('start',()=>{state.previewCamera=false;state.dirty=true;});controls.addEventListener('change',()=>{state.drawPending=true;});
 new ResizeObserver(()=>{if(state.recording)return;const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();state.drawPending=true;drawTimeline();}).observe(canvas);
 canvas.addEventListener('dblclick',pickBone);
 let lastRender=0;function animate(now){if(state.serviceStopped)return;requestAnimationFrame(animate);if(state.offlineExport)return;if(now-lastRender<1000/state.outputFPS-.5)return;lastRender=now;const dt=Math.min(.1,(now-lastTick)/1000);lastTick=now;if(state.playing){let frame=state.frame+dt*30*state.speed;if(audioURL)frame=audioTrack?.clock(frame/30,state.speed)*30||frame;if(frame>state.duration){if(state.loop&&!state.recording){frame%=state.duration;audioTrack?.seek(frame/30,true);}else{frame=state.duration;togglePlay(false);if(recorder?.state==='recording')recorder.stop();}}setFrame(frame,false);}
  const updated=state.dirty;if(updated&&!featureController?.isExtracting())apply();controls.enabled=!state.modelDragging&&!state.recording;const moved=controls.enabled&&controls.update();for(const h of skeletons)h.visible=$('skeletonToggle').getAttribute('aria-pressed')==='true';
  if(state.playing||state.recording||updated||moved||state.drawPending){renderer.shadowMap.enabled=ground.visible&&$('enableShadow').checked;renderScene($('enableOutline').checked);state.drawPending=false;state.renderedFrames=(state.renderedFrames||0)+1;}
  if(now-(state.statsTime||0)>=1000){const fps=Math.round((state.renderedFrames||0)*1000/(now-(state.statsTime||now-1000)));$('viewportStats').textContent=(state.model?state.model.bones.length+' 骨骼 · ':'')+(state.playing?fps+' fps': '已暂停');state.renderedFrames=0;state.statsTime=now;}
  if(now-lastInspector>120){updateInspector();lastInspector=now;}
 }
 requestAnimationFrame(animate);
}
async function rebuild(savedSettings,savedMapping,savedSource){const generation=++state.loadGeneration;await togglePlay(false);setLoading(true);status('正在读取 Unity 原生组件…');
 try{if(/^\d+$/.test(state.components.body)&&!state.catalog.characters.some(p=>p.id===state.profile?.id))state.profile=state.catalog.characters.find(p=>p.face===state.components.face)||state.catalog.characters[0];const model=await resolveExtraModel(state.components.body)||await createCharacter({...state.components},state.profile,state.variants);if(state.components.body==='unity-standard'||state.components.body.startsWith('imported:'))state.profile=model.profile;if(generation!==state.loadGeneration){model.dispose();return;}
  if(state.model)state.model.dispose();for(const h of skeletons){h.removeFromParent();h.dispose();}skeletons=[];state.model=model;await customAccessories?.rebuild();state.retarget=new Retargeter(model);sceneTools.attach(model);if(savedSettings)Object.assign(state.retarget.settings,savedSettings);if(savedMapping)state.retarget.mapping={...state.retarget.mapping,...savedMapping};if(savedSource)state.retarget.calibrate(savedSource);
  for(const part of model.parts){const helper=new THREE.SkeletonHelper(part.group);helper.material.depthTest=false;helper.material.transparent=true;helper.material.opacity=.8;scene.add(helper);skeletons.push(helper);}
  $('modelLabel').textContent=state.profile?.name||'自定义角色';$('viewportStats').textContent=`${model.bones.length} 骨骼 · ${model.meshes.reduce((s,m)=>s+m.geometry.attributes.position.count,0).toLocaleString()} 顶点`;
  $('projectName').textContent=state.profile?.name+' · 动画工程';$('modelInfo').textContent=`${model.bones.length} 个原生骨骼\n${model.morphs.length} 个脸部表情\n${model.meshes.length} 个网格\n蒙皮矩阵误差 ${model.bindError.toExponential(1)}`;$('modelInfo').style.whiteSpace='pre-line';
  renderBones();renderMorphs();renderMapping();renderMaterials();updateRetargetFields();updateExtraUI(state);report();state.dirty=true;setLoading(false);status('角色已组装 · 可以载入动作或选择骨骼编辑');if(state.selection&&!model.bones.some(b=>b.userData.key===state.selection.key)&&!model.morphs.some(m=>m.key===state.selection.key))state.selection=null;
  trackEditor?.refresh();changed();
 }catch(e){setLoading(false);fail(e);throw e;}}
function setupCatalog(catalog){state.catalog=catalog;state.profile=catalog.characters[0]||{id:'unity-standard',name:'标准 Unity 人形',bodyScale:1,headScale:1};if(!catalog.characters.length)state.components={body:'unity-standard',face:'',hair:'',skin:'',accessory:'',faceAccessory:'',backAccessory:''};$('characterCount').textContent=catalog.characters.length+' 位';
 for(const p of catalog.characters){const button=document.createElement('button');button.className='character';button.dataset.id=p.id;button.style.setProperty('--character-color',p.color&&p.color.startsWith('#')?p.color:'#b5a1ff');const avatar=document.createElement('span');avatar.className='avatar';avatar.textContent=p.name.replaceAll(' ','').slice(0,1);button.append(avatar,document.createTextNode(p.name));button.onclick=async()=>{state.profile=p;state.components.face=p.face;state.components.hair=p.hair;state.components.skin=p.skin;syncComponents();updateVariants();await rebuild(state.retarget?.settings,state.retarget?.mapping,state.retarget?.sourcePositions);};$('characters').append(button);}
 for(const family of ['body','hair','face','accessory','faceAccessory','backAccessory','skin']){const select=$(family+'Select');if(family.toLowerCase().includes('accessory'))select.add(new Option('无配饰',''));for(const m of catalog.models.filter(m=>m.family===(family.endsWith('Accessory')?'accessory':family)&&m.available&&(family==='faceAccessory'?m.id.startsWith('3'):family==='backAccessory'?m.id.startsWith('4'):family==='accessory'?m.id.startsWith('2'):true)))select.add(new Option(m.label,m.id));select.onchange=()=>{state.components[family]=select.value;updateVariants();rebuild(state.retarget?.settings,state.retarget?.mapping,state.retarget?.sourcePositions);};}
 for(const m of catalog.motions.filter(m=>m.kind==='vmd'&&!/相机|镜头|camera/i.test(m.name+' '+m.path)))$('motionSelect').add(new Option(m.displayPath||m.path,m.id));$('resourceInfo').textContent=`${catalog.counts.body} 套服装 · ${catalog.counts.hair} 套发型\n${catalog.counts.accessory} 套头饰 · ${catalog.motions.filter(m=>m.kind==='vmd').length} 个动作`;$('resourceInfo').style.whiteSpace='pre-line';setupAudioLibrary();syncComponents();updateVariants();}
function syncComponents(){for(const [f,id] of Object.entries(state.components))$(f+'Select').value=id;for(const b of $('characters').children)b.classList.toggle('active',b.dataset.id===state.profile?.id);}
function switchTab(side,tab){document.querySelectorAll(`[data-${side}]`).forEach(b=>b.classList.toggle('active',b.dataset[side]===tab));for(const n of side==='left'?['assets','bones','morphs']:['inspector','retarget','scene','tracks'])$(n+'Panel').classList.toggle('hidden',n!==tab);}
function renderBones(){const list=$('boneList');list.replaceChildren();const search=$('boneSearch').value.toLowerCase();for(const b of state.model.bones){const m=state.retarget.mapping[b.name]||'';if(!(b.name+' '+m).toLowerCase().includes(search))continue;const button=document.createElement('button');button.dataset.key=b.userData.key;button.textContent=zh(b.name);const small=document.createElement('small');small.textContent=zh(m)||b.userData.family;button.append(small);button.onclick=()=>select({type:'bone',key:b.userData.key});list.append(button);}updateSelectedList();}
function shortMorph(name){return name.replace(/^BS_Face\.BS_/,'');}
function renderMorphs(){const list=$('morphList');list.replaceChildren();const search=$('morphSearch').value.toLowerCase();for(const m of state.model.morphs){if(!m.name.toLowerCase().includes(search))continue;const b=document.createElement('button');b.dataset.key=m.key;b.textContent=shortMorph(m.name);b.onclick=()=>select({type:'morph',key:m.key});list.append(b);}updateSelectedList();}
function updateSelectedList(){for(const b of [...$('boneList').children,...$('morphList').children])b.classList.toggle('active',b.dataset.key===state.selection?.key);}
function select(item){state.selection=item;switchTab('right','inspector');if(innerWidth<800)document.querySelector('.right-panel').classList.add('mobile-visible');updateSelectedList();updateInspector();drawTimeline();}
function selectedBone(){return state.selection?.type==='bone'?state.model.bones.find(b=>b.userData.key===state.selection.key):null;}
function selectedMorph(){return state.selection?.type==='morph'?state.model.morphs.find(m=>m.key===state.selection.key):null;}
function updateInspector(){if(!state.model)return;const b=selectedBone(),m=selectedMorph();$('noSelection').classList.toggle('hidden',!!(b||m));$('boneInspector').classList.toggle('hidden',!b);$('morphInspector').classList.toggle('hidden',!m);$('selectedTitle').textContent=m?'表情属性':'骨骼属性';$('selectedFamily').textContent=b?.userData.family||'';
 if(b){$('selectedName').textContent=zh(b.name)+(state.retarget.mapping[b.name]?' · '+zh(state.retarget.mapping[b.name]):'');const delta=b.userData.rest.quaternion.clone().invert().multiply(b.quaternion),e=new THREE.Euler().setFromQuaternion(delta,'XYZ');const a=[e.x,e.y,e.z].map(THREE.MathUtils.radToDeg);const p=b.position.clone().sub(b.userData.rest.position).toArray();for(let i=0;i<3;i++){for(const prefix of ['rot','pos']){const v=prefix==='rot'?a[i]:p[i];if(document.activeElement!==$(prefix+i))$(prefix+i).value=v.toFixed(prefix==='rot'?1:3);if(document.activeElement!==$(prefix+'Range'+i))$(prefix+'Range'+i).value=v;}}$('editTrackLabel').firstChild.textContent=zh(b.name)+' ';}
 else if(m){$('morphName').textContent=shortMorph(m.name);const v=m.mesh.morphTargetInfluences[m.index];if(document.activeElement!==$('morphWeight'))$('morphWeight').value=v;$('morphValue').textContent=v.toFixed(2);$('editTrackLabel').firstChild.textContent=shortMorph(m.name)+' ';}
 else $('editTrackLabel').firstChild.textContent='当前选择 ';}
function setupPoseFields(){for(const [prefix,label,min,max,step] of [['rot','rotationFields',-180,180,.1],['pos','positionFields',-.5,.5,.001]])for(let i=0;i<3;i++){
 const row=document.createElement('label');row.className='axis-field';const axis=document.createElement('span');axis.textContent=['X','Y','Z'][i];const range=document.createElement('input');range.id=prefix+'Range'+i;range.type='range';range.min=min;range.max=max;range.step=step;range.value=0;range.setAttribute('aria-label',prefix+' '+axis.textContent);
 const number=document.createElement('input');number.id=prefix+i;number.type='number';number.step=step;number.value=0;number.setAttribute('aria-label',prefix+' '+axis.textContent+' 数值');row.append(axis,range,number);$(label).append(row);
 const set=()=>{const b=selectedBone();if(!b)return;pushHistory();const arr=[0,1,2].map(n=>Number($(prefix+n).value)||0);if(prefix==='rot')b.quaternion.copy(b.userData.rest.quaternion).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(...arr.map(THREE.MathUtils.degToRad),'XYZ')));else b.position.copy(b.userData.rest.position).add(new THREE.Vector3().fromArray(arr));writeBoneKey(b);};
 number.onchange=()=>{range.value=number.value;set();};range.oninput=()=>{number.value=range.value;};range.onchange=set;
 }
 // Native keyframe interpolation is edited on the same selected track.
 const block=document.createElement('div');block.className='curve-block';block.innerHTML='<div class="property-title">关键帧插值 <span>当前帧 → 前一帧</span></div><select id="curvePreset"><option value="linear">线性</option><option value="ease">平滑缓入缓出</option><option value="in">缓入</option><option value="out">缓出</option></select><canvas id="curveCanvas" width="220" height="96" aria-label="关键帧贝塞尔曲线"></canvas>';$('boneInspector').append(block);$('curvePreset').onchange=()=>{const b=selectedBone();if(!b)return;const key=state.edits.bones[b.userData.key]?.find(k=>k.frame===Math.round(state.frame));if(!key){toast('先在当前帧插入关键帧，再修改插值');return;}pushHistory();key.curve={linear:[20,20,107,107],ease:[42,0,85,127],in:[64,0,127,127],out:[0,0,64,127]}[$('curvePreset').value];changed();drawCurve(key.curve);};drawCurve();
}
function drawCurve(curve=[20,20,107,107]){const c=$('curveCanvas');if(!c)return;const x=c.getContext('2d');x.fillStyle='#222431';x.fillRect(0,0,220,96);x.strokeStyle='#414251';x.lineWidth=1;for(let i=0;i<5;i++){x.beginPath();x.moveTo(15+i*47.5,8);x.lineTo(15+i*47.5,85);x.moveTo(15,8+i*19.25);x.lineTo(205,8+i*19.25);x.stroke();}x.strokeStyle='#b09eff';x.lineWidth=2;x.beginPath();x.moveTo(15,85);x.bezierCurveTo(15+curve[0]/127*190,85-curve[1]/127*77,15+curve[2]/127*190,85-curve[3]/127*77,205,8);x.stroke();}
function writeBoneKey(b){const key={frame:Math.round(state.frame),position:b.position.toArray(),quaternion:b.quaternion.toArray(),curve:[20,20,107,107]},keys=state.edits.bones[b.userData.key]??=[];const i=keys.findIndex(k=>k.frame===key.frame);if(i>=0){key.curve=keys[i].curve||key.curve;keys[i]=key;}else keys.push(key);keys.sort((a,b)=>a.frame-b.frame);changed();drawTimeline();status(`${b.name} · 已记录第 ${key.frame} 帧`);drawCurve(key.curve);}
function writeMorphKey(m){const key={frame:Math.round(state.frame),weight:Number($('morphWeight').value)},keys=state.edits.morphs[m.key]??=[];const i=keys.findIndex(k=>k.frame===key.frame);if(i>=0)keys[i]=key;else keys.push(key);keys.sort((a,b)=>a.frame-b.frame);changed();drawTimeline();}
function deleteKey(){const s=state.selection;if(!s)return;const dict=s.type==='bone'?state.edits.bones:state.edits.morphs,keys=dict[s.key];if(!keys?.some(k=>k.frame===Math.round(state.frame))){toast('当前帧没有手动编辑的关键帧');return;}pushHistory();dict[s.key]=keys.filter(k=>k.frame!==Math.round(state.frame));changed();drawTimeline();}
function renderMapping(){const list=$('mappingList');list.replaceChildren();for(const name of [...new Set(state.model.bones.map(b=>b.name))].sort((a,b)=>Number(!!state.retarget.mapping[b])-Number(!!state.retarget.mapping[a]))){const mmd=state.retarget.mapping[name]||'';const row=document.createElement('div');row.className='mapping-row';const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.value=mmd;input.setAttribute('aria-label',name+' 对应 MMD 骨骼');input.onchange=()=>{state.retarget.mapping[name]=input.value.trim();changed();report();renderBones();};row.append(label,input);list.append(row);}}
function updateRetargetFields(){const s=state.retarget.settings;$('motionScale').value=s.scale.toFixed(4);$('armAngle').value=s.armAngle;$('armAngleValue').textContent=s.armAngle+'°';$('enableIK').checked=s.ik;$('enableRoot').checked=s.rootMotion;$('enableCloth').checked=s.cloth!==false;$('clothInertia').value=s.clothInertia??.65;$('clothWind').value=s.clothWind??0;$('clothMargin').value=s.clothMargin??.006;$('enableSecondary').checked=s.secondary!==false;$('secondaryStrength').value=s.secondaryStrength??.65;$('sourceRig').value=state.retarget.sourcePositions?'custom':'canonical';}
function report(){if(!state.retarget)return;const r=state.retarget.diagnostics(state.motion);$('mappingCount').textContent=r.mapped+' 条已使用';$('diagnostics').replaceChildren();const main=document.createElement('div');main.textContent=`已映射 ${r.mapped} 条骨骼轨道\n${Object.keys(state.motion.morphs).length-r.morphs.length} 条表情轨道\n${state.cameraTrack?.keys?.length||0} 个独立镜头关键帧`;main.style.whiteSpace='pre-line';$('diagnostics').append(main);
 for(const [title,names] of [['未映射骨骼',r.unmapped],['未映射表情',r.morphs]])if(names.length){const el=document.createElement('div');el.className='warning';el.textContent=title+'：'+names.join('、');$('diagnostics').append(el);}
 if(state.retarget.rig.missing.length){const warning=document.createElement('div');warning.className='warning';warning.textContent='必要关节未识别：'+state.retarget.rig.missing.join('、');$('diagnostics').append(warning);}const note=document.createElement('div');note.className='hint';note.textContent='布料采用 XPBD 拉伸与弯曲约束、惯性、阻尼和腿部碰撞。拖动时间轴会重置惯性；视频包含布料效果，GLB / PMX 导出保留原生骨骼。';$('diagnostics').append(note);}
function renderMaterials(){const list=$('materialsList');list.replaceChildren();for(const item of state.model.materials){const row=document.createElement('label');row.className='material-row';const toggle=document.createElement('input');toggle.type='checkbox';const override=state.materialOverrides[item.key];if(override){item.material.visible=override.visible;item.material.color.set(override.color);}toggle.checked=item.material.visible;toggle.setAttribute('aria-label',item.key+' 可见');toggle.onchange=()=>{item.material.visible=toggle.checked;state.materialOverrides[item.key]={visible:toggle.checked,color:'#'+item.material.color.getHexString()};changed();};const label=document.createElement('span');label.textContent=item.key;const color=document.createElement('input');color.type='color';color.value='#'+item.material.color.getHexString();color.setAttribute('aria-label',item.key+' 颜色');color.oninput=()=>{item.material.color.set(color.value);state.materialOverrides[item.key]={visible:item.material.visible,color:color.value};changed();};row.append(toggle,label,color);list.append(row);}}
function timelineRows(){if(trackEditor)return trackEditor.rows();const bone=selectedBone(),morph=selectedMorph();const source=bone&&state.retarget.mapping[bone.name];return [source?state.motion.bones[source]||[]:Object.values(state.motion.bones).flat(),morph?Object.entries(state.motion.morphs).filter(([n])=>morph.name.endsWith('BS_'+MORPH_MAPPING[n])||morph.name===n).flatMap(([,k])=>k):Object.values(state.motion.morphs).flat(),(state.cameraTrack?.keys||[]).map(k=>({frame:k.frame+(sceneTools?.timelineCamera().offset||0)*30})),state.selection?(state.selection.type==='bone'?state.edits.bones:state.edits.morphs)[state.selection.key]||[]:[]];}
function timelineScale(){return Math.min(Number($('timelineZoom').value),14000/Math.max(state.duration,1));}
let lastTimelineDraw=0;function drawTimeline(){const now=performance.now();if(state.playing&&!state.scrubbing&&now-lastTimelineDraw<1000/30)return;lastTimelineDraw=now;const c=$('timelineCanvas');if(!c)return;const px=timelineScale(),width=Math.max($('timelineScroll').clientWidth,state.duration*px+40),ratio=Math.min(devicePixelRatio,2);c.style.width=width+'px';if(c.width!==Math.ceil(width*ratio)||c.height!==Math.ceil(184*ratio)){c.width=Math.ceil(width*ratio);c.height=Math.ceil(184*ratio);}const x=c.getContext('2d');x.setTransform(ratio,0,0,ratio,0,0);x.clearRect(0,0,width,184);x.fillStyle='#1c1e28';x.fillRect(0,0,width,184);
 const major=Math.max(30,Math.ceil(75/px/30)*30),minor=major/6;for(let f=0;f<=state.duration;f+=minor){const xpos=20+f*px,isMajor=f%major===0;x.strokeStyle=isMajor?'#383b4c':'#292c39';x.beginPath();x.moveTo(xpos,isMajor?0:22);x.lineTo(xpos,184);x.stroke();if(isMajor){x.fillStyle='#7f8aa9';x.font='10px Consolas,monospace';x.fillText(String(Math.round(f)),xpos+4,17);}}
 for(let i=0;i<6;i++){x.strokeStyle='#303344';x.beginPath();x.moveTo(0,29+i*31);x.lineTo(width,29+i*31);x.stroke();}
 const native=!!state.motion.gameMotion;document.querySelector('[data-track=motion] small').textContent=native?'Unity':'VMD';document.querySelector('[data-track=morph] small').textContent=native?'Unity':'VMD';document.querySelector('[data-track=camera] small').textContent=state.cameraTrack?.format==='game-camera'?'Unity':state.cameraTrack?.format==='nananiji-camera'?'相机':'VMD';for(const row of native?[...(state.motion.disabledBody?[]:[0]),...(state.motion.disabledFace?[]:[1])]:[]){x.fillStyle=row?'#294642':'#3a344e';x.fillRect(20,34+row*31,state.duration*px,20);x.fillStyle='#b6a8dd';x.font='10px sans-serif';x.fillText(row?'Unity 原生表情':'Unity 原生身体动作',24,48+row*31);}if(state.cameraTrack?.format==='game-camera'){const t=sceneTools.timelineCamera();x.fillStyle='#2d394a';x.fillRect(20+t.offset*30*px,96,t.duration*30*px,20);x.fillStyle='#9db1cc';x.fillText('Unity 原游戏镜头',24+t.offset*30*px,110);}const colors=['#9384cf','#72b5af','#718bab','#c6adff'];timelineRows().forEach((keys,row)=>{const columns=new Set(keys.map(k=>Math.round(20+k.frame*px)));x.fillStyle=colors[row];for(const xpos of columns){const active=trackEditor?.selected();x.fillStyle=active&&Math.round(20+active.frame*px)===xpos?'#f6d18a':colors[row];const y=44+row*31;x.beginPath();x.moveTo(xpos,y-4);x.lineTo(xpos+4,y);x.lineTo(xpos,y+4);x.lineTo(xpos-4,y);x.closePath();x.fill();}});
 audioTrack?.draw(x,px,width,168);const play=20+state.frame*px;x.strokeStyle='#e0b7c7';x.lineWidth=1.4;x.beginPath();x.moveTo(play,0);x.lineTo(play,184);x.stroke();x.fillStyle='#e0b7c7';x.beginPath();x.moveTo(play-5,0);x.lineTo(play+5,0);x.lineTo(play+5,15);x.lineTo(play,20);x.lineTo(play-5,15);x.fill();}
function setupTimeline(){$('loop').after($('fitTimeline'));let drag=null;const c=$('timelineCanvas');c.tabIndex=0;c.ondblclick=async e=>{const r=c.getBoundingClientRect(),row=Math.floor((e.clientY-r.top-29)/31),frame=Math.round((e.clientX-r.left-20)/timelineScale());if(row<0||row>3)return;await trackEditor.choose(row,frame);setFrame(frame);trackEditor.insert();};
 c.onpointerdown=async e=>{if(!state.model||state.recording)return;const wasPlaying=state.playing;await togglePlay(false);state.scrubbing=true;c.focus();const r=c.getBoundingClientRect(),frame=Math.round((e.clientX-r.left-20)/timelineScale()),y=e.clientY-r.top,row=Math.floor((y-29)/31);drag={scrub:true,resume:wasPlaying};c.setPointerCapture(e.pointerId);setFrame(frame);if(row>=0&&row<4&&trackEditor){const selected=await trackEditor.choose(row,frame);if(selected&&drag){drag={...selected,resume:wasPlaying,delta:selected.key.frame+selected.offset-frame};setFrame(selected.key.frame+selected.offset);}}};
 c.onpointermove=e=>{if(!drag)return;const frame=Math.max(0,Math.min(state.duration,Math.round((e.clientX-c.getBoundingClientRect().left-20)/timelineScale())));if(drag.key){drag.key.frame=Math.max(0,Math.round(frame+drag.delta-drag.offset));setFrame(drag.key.frame+drag.offset);changed();drawTimeline();}else setFrame(frame);};
 const finish=()=>{const resume=drag?.resume;if(drag?.key){drag.keys.sort((a,b)=>a.frame-b.frame);for(let i=drag.keys.length-1;i>=0;i--)if(drag.keys[i]!==drag.key&&drag.keys[i].frame===drag.key.frame)drag.keys.splice(i,1);trackEditor.moved();}drag=null;state.scrubbing=false;if(resume)togglePlay(true);};c.onpointerup=finish;c.onpointercancel=finish;
 $('timelineZoom').oninput=drawTimeline;$('fitTimeline').onclick=()=>{$('timelineZoom').value=Math.max(.05,($('timelineScroll').clientWidth-40)/Math.max(1,state.duration));$('timelineScroll').scrollLeft=0;drawTimeline();};}

async function importMotion(buffer,name){const clip=parseVMD(buffer,name);const body=Object.keys(clip.bones).length,morph=Object.keys(clip.morphs).length;
 if(clip.cameras.length)await sceneTools.setTrack({format:'mmd-camera',name:name||'MMD 镜头',keys:clip.cameras});clip.cameras=[];
 if(body){state.motion=clip;state.edits={bones:{},morphs:{}};state.duration=Math.max(1,clip.duration,state.cameraTrack?.keys?.at(-1)?.frame||0);state.history=[];state.future=[];updateHistory();await sceneTools.syncSong();}
 else if(morph){Object.assign(state.motion.morphs,clip.morphs);state.duration=Math.max(state.duration,clip.duration);}
 else if(!state.cameraTrack)throw new Error('文件没有可使用的轨道');
 refreshMotion();setFrame(0);report();changed();status(body?'身体动作已载入 · 镜头轨道独立保留':'独立轨道已载入 · 身体动作保留');}
async function openProject(p){state.lighting=p.lighting||{};validateProject(p);if((p.renderVersion||0)<7&&p.ensemble&&p.motion.gameMotion){const song=p.motion.gameMotion.id.split('-')[0];for(const a of p.ensemble.actors||[])a.slot=roleSlot(state.catalog,song,a.slot);p.ensemble.primary??={position:[0,0,0],rotation:0};p.ensemble.primary.slot=roleSlot(state.catalog,song,p.motion.gameMotion.id.split('-')[1]);}state.restoring=true;document.body.classList.add('restoring');setLoading(true,'正在恢复角色、舞台和轨道');try{state.autoGameStage=p.autoGameStage!==false;$('autoGameStage').checked=state.autoGameStage;state.rendering=p.rendering||{};if((p.renderVersion||0)<6&&state.rendering.style==='anime')state.rendering=renderPreset('anime');$('videoEncoder').value=p.videoEncoder||'auto';$('videoPipeline').value=String(p.videoPipeline||4);state.videoResolution=p.videoResolution||'1920x1080';$('videoResolution').value=state.videoResolution;state.filter=p.filter||'original';state.filterStrength=p.filterStrength??1;state.greenScreen=!!p.greenScreen;state.backgroundFit=p.backgroundFit||'contain';state.sceneCollapsed=p.sceneCollapsed||{};$('timelineZoom').value=p.timelineZoom||Math.max(.05,($('timelineScroll').clientWidth-40)/Math.max(1,p.duration||300));state.customAccessories=p.customAccessories||[];state.backgroundLibrary=p.backgroundLibrary||[];appearance?.restore();$('mp4IncludeAudio').checked=p.mp4IncludeAudio!==false;state.previewQuality=p.previewQuality||'smooth';$('previewQuality').value=state.previewQuality;setPreviewQuality();state.outputFPS=p.outputFPS===30?30:60;$('outputFPS').value=String(state.outputFPS);if((p.renderVersion||0)<5&&p.retarget?.settings){p.retarget.settings.scale=.08;}if((p.renderVersion||0)<2){if(p.retarget?.settings)p.retarget.settings.clothMargin=.006;if(p.scene)p.scene.light=1;}state.components=p.components;state.materialOverrides=p.materialOverrides||{};state.variants=p.variants||{body:'01',accessory:'01',subwear:'01'};updateVariants();state.profile=p.profile||state.catalog.characters[0];if(p.motion.gameMotion)await loadGameMotion(p.motion.gameMotion.id);state.motion=p.motion;state.motion.name=zh(state.motion.name);state.edits=p.edits;state.duration=p.duration||p.motion.duration||300;state.history=[];state.future=[];syncComponents();await rebuild(p.retarget?.settings,p.retarget?.mapping,p.retarget?.sourcePositions);await sceneTools.restore(p);audioTrack.offset=p.audioOffset||0;$('audioOffset').value=audioTrack.offset;
 if(p.scene){$('backgroundColor').value=p.scene.background||'#262937';scene.background=new THREE.Color($('backgroundColor').value);$('enableOutline').checked=p.scene.outline??true;$('enableShadow').checked=p.scene.shadow??true;ground.visible=$('enableShadow').checked;$('enableCamera').checked=(p.scene.cameraMotion??false)&&!!state.cameraTrack;keyLight.intensity=p.scene.light??1;previewLight.intensity.value=keyLight.intensity;$('lightIntensity').value=keyLight.intensity;if(p.scene.camera){camera.position.fromArray(p.scene.camera.position);controls.target.fromArray(p.scene.camera.target);camera.fov=p.scene.camera.fov;camera.updateProjectionMatrix();controls.update();}}
 if(p.scene){$('lightAzimuth').value=p.scene.lightAzimuth??-34;$('lightElevation').value=p.scene.lightElevation??42;updateLight();}try{await featureController?.restoreBackground(p.background);await featureController?.restoreBackgroundImage(p.backgroundImage);appearance?.restore();}catch(e){toast('背景需重新导入：'+e.message);}
 $('gameMotionSelect').value=state.motion.gameMotion?.id||'';$('projectName').textContent=p.name||'未命名工程';$('clipName').textContent=zh(p.motion.name);$('durationInput').value=state.duration;setFrame(0);updateHistory();$('motionSummary').textContent=`${p.motion.name} · ${state.duration} 帧`;clearAudio();if(p.audioFile){const files=await getFiles(p.audioFile.id);await loadAudio(files.find(f=>f.name===p.audioFile.name)||files[0],p.audioFile);}else if(p.audioId){const item=state.catalog.motions.find(m=>m.id===p.audioId&&m.kind==='audio');if(item)loadAudioLibrary(item);}status('工程已恢复');}finally{state.restoring=false;document.body.classList.remove('restoring');setLoading(false);changed();}}
function pickBone(event){if(!state.model)return;const rect=canvas.getBoundingClientRect(),mouse=new THREE.Vector2((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);let best=null,distance=20;const point=new THREE.Vector3();for(const b of state.model.bones){b.getWorldPosition(point);point.project(camera);if(point.z<-1||point.z>1)continue;const d=Math.hypot((point.x-mouse.x)*rect.width/2,(point.y-mouse.y)*rect.height/2);if(d<distance){distance=d;best=b;}}if(best){switchTab('left','bones');select({type:'bone',key:best.userData.key});}}
async function bakeNative(){const previous=state.frame;await togglePlay(false);setLoading(true,'正在烘焙 Unity 动画');const bones=state.model.bones,parts=state.model.parts.filter(p=>p.data.attachmentMatrix),boneTracks={},partTracks={},morphTracks={},fps=state.outputFPS;
 for(const b of bones)boneTracks[b.userData.key]={name:b.name,position:[],quaternion:[]};for(const p of parts)partTracks[p.family]={position:[],quaternion:[],scale:[]};for(const m of state.model.morphs)morphTracks[m.key]=[];
 const times=[],rootKeys={position:[],quaternion:[]},count=Math.ceil(state.duration*fps/30);
 for(let i=0;i<=count;i++){const frame=Math.min(state.duration,i*30/fps);state.retarget.apply(state.motion,frame,state.edits);times.push(frame/30);
  for(const b of bones){boneTracks[b.userData.key].position.push(...b.position.toArray());boneTracks[b.userData.key].quaternion.push(...b.quaternion.toArray());}
  for(const p of parts){partTracks[p.family].position.push(...p.group.position.toArray());partTracks[p.family].quaternion.push(...p.group.quaternion.toArray());partTracks[p.family].scale.push(...p.group.scale.toArray());}
  for(const m of state.model.morphs)morphTracks[m.key].push(m.mesh.morphTargetInfluences[m.index]);rootKeys.position.push(...state.model.motionRoot.position.toArray());rootKeys.quaternion.push(...state.model.motionRoot.quaternion.toArray());
  if(i%100===0){status('动画烘焙 '+Math.round(i/count*100)+'%');await new Promise(r=>setTimeout(r,0));}
 }
 setFrame(previous);apply();setLoading(false);return {format:'nananiji-native-animation',version:1,fps,duration:state.duration/30,source:state.motion.name,components:state.components,times,bones:boneTracks,attachments:partTracks,morphs:morphTracks,root:rootKeys};}
async function exportGLB(){if(!state.model)return;try{const baked=await bakeNative(),tracks=[],times=baked.times,model=state.model;
 for(const b of model.bones){const keys=baked.bones[b.userData.key];tracks.push(new THREE.VectorKeyframeTrack(b.uuid+'.position',times,keys.position),new THREE.QuaternionKeyframeTrack(b.uuid+'.quaternion',times,keys.quaternion));}
 for(const p of model.parts){const k=baked.attachments[p.family];if(k)tracks.push(new THREE.VectorKeyframeTrack(p.group.uuid+'.position',times,k.position),new THREE.QuaternionKeyframeTrack(p.group.uuid+'.quaternion',times,k.quaternion),new THREE.VectorKeyframeTrack(p.group.uuid+'.scale',times,k.scale));}
 for(const mesh of model.meshes){if(!mesh.morphTargetInfluences?.length)continue;const values=[];for(let i=0;i<times.length;i++)for(const m of model.morphs.filter(m=>m.mesh===mesh))values.push(baked.morphs[m.key][i]);tracks.push(new THREE.NumberKeyframeTrack(mesh.uuid+'.morphTargetInfluences',times,values));}
 tracks.push(new THREE.VectorKeyframeTrack(model.motionRoot.uuid+'.position',times,baked.root.position),new THREE.QuaternionKeyframeTrack(model.motionRoot.uuid+'.quaternion',times,baked.root.quaternion));
 const clip=new THREE.AnimationClip(state.motion.name,state.duration/30,tracks);setLoading(true,'正在打包 GLB');restoreClothGeometry(model);resetBones(model.bones);model.motionRoot.position.set(0,0,0);model.motionRoot.quaternion.identity();model.updateAttachments();model.motionRoot.updateMatrixWorld(true);const output=await new GLTFExporter().parseAsync(model.motionRoot,{binary:true,animations:[clip],onlyVisible:false});apply();download(output,'22-7-'+state.profile.id+'.glb');setLoading(false);toast('GLB 已导出：原生蒙皮、表情与骨骼动画；裙面碰撞修正在网页预览中计算。');status('GLB 导出完成');}catch(e){apply();setLoading(false);fail(e);}}
async function exportVMD(){try{
 // Original VMD tracks and all unsupported records round-trip without loss.
 // Native edits are encoded back into corresponding MMD local channels.
 const out=structuredClone(state.motion),previous=state.frame;out.cameras=state.cameraTrack?.format==='mmd-camera'?structuredClone(state.cameraTrack.keys):[];await togglePlay(false);setLoading(true,'正在生成 VMD');
 const changedBones=Object.entries(state.edits.bones).filter(([,k])=>k.length);
 if(changedBones.length){const targets=new Set(changedBones.map(([key])=>state.model.bones.find(b=>b.userData.key===key)).filter(Boolean));
  // Baking every mapped bone also compensates descendants and the torso's different hierarchy.
  const mapped=state.model.bodyBones.filter(b=>state.retarget.mapping[b.name]);for(const b of mapped)out.bones[state.retarget.mapping[b.name]]=[];
  const getDelta=b=>{const q=b.getWorldQuaternion(new THREE.Quaternion());return state.model.motionRoot.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(q).multiply(b.userData.rest.worldQuaternion.clone().invert());};
  const parentName={'下半身':null,'上半身':null,'上半身2':'上半身','首':'上半身2','頭':'首'};for(const s of ['左','右'])Object.assign(parentName,{[s+'肩']:'上半身2',[s+'腕']:s+'肩',[s+'腕捩']:s+'腕',[s+'ひじ']:s+'腕捩',[s+'手捩']:s+'ひじ',[s+'手首']:s+'手捩',[s+'足']:'下半身',[s+'ひざ']:s+'足',[s+'足首']:s+'ひざ'});
  for(let frame=0;frame<=state.duration;frame++){state.retarget.apply(state.motion,frame,state.edits);const deltas=new Map();for(const b of mapped){let q=getDelta(b);if(state.retarget.alignments()[b.name])q.multiply(state.retarget.alignments()[b.name].clone().invert());deltas.set(state.retarget.mapping[b.name],q);}
   for(const b of mapped){const name=state.retarget.mapping[b.name];let parent=MMD_PARENT[name]??parentName[name];while(parent&&!deltas.has(parent))parent=MMD_PARENT[parent];if(!parent&&name.match(/^[左右].*[０１２３]$/)){const n=name.at(-1),prev={'１':'０','２':'１','３':'２'}[n];parent=prev&&deltas.has(name.slice(0,-1)+prev)?name.slice(0,-1)+prev:name[0]+'手首';}
    const q=(deltas.get(parent)?.clone().invert()||new THREE.Quaternion()).multiply(deltas.get(name));out.bones[name].push({frame,position:[0,0,0],quaternion:[q.x,-q.y,-q.z,q.w],interpolation:linearInterpolation()});}
   if(frame%100===0)await new Promise(r=>setTimeout(r,0));
  }
  if([...targets].some(b=>state.edits.bones[b.userData.key].some(k=>new THREE.Vector3().fromArray(k.position).distanceTo(b.userData.rest.position)>.0001)))toast('VMD 已回写旋转。Unity 骨骼局部位移请使用 GLB 或动画 JSON 保留。');
  if([...targets].some(b=>!state.retarget.mapping[b.name]))toast('未映射骨骼的编辑仅保存在工程、GLB 和动画 JSON 中。');
 }
 for(const [key,keys] of Object.entries(state.edits.morphs)){const m=state.model.morphs.find(m=>m.key===key);if(!m)continue;const name=Object.entries(MORPH_MAPPING).find(([,v])=>m.name.endsWith('BS_'+v))?.[0];if(name)out.morphs[name]=structuredClone(keys);}
 download(writeVMD(out),'22-7-motion.vmd');setFrame(previous);apply();setLoading(false);status('VMD 已导出');
 }catch(e){setLoading(false);fail(e);}}

function setupAudioLibrary(){const select=document.createElement('select');select.id='audioLibrary';select.setAttribute('aria-label','内置歌曲');select.add(new Option('内置歌曲…',''));for(const m of state.catalog.motions.filter(m=>m.kind==='audio'))select.add(new Option(m.name,m.id));select.onchange=()=>{const item=state.catalog.motions.find(m=>m.id===select.value);if(item)loadAudioLibrary(item);};$('audioName').parentElement.before(select);}
function clearAudio(){audio.pause();if(audioURL?.startsWith('blob:'))URL.revokeObjectURL(audioURL);audioURL=null;audioTrack?.clear();state.audioFile=null;audio.removeAttribute('src');audio.load();$('audioLibrary').value='';$('audioName').textContent='未载入音频';}
function loadAudioLibrary(item){state.audioFile=null;if(audioURL)URL.revokeObjectURL(audioURL);audioURL=item.url||'/api/motion/'+item.id;audio.src=audioURL;audio.load();audioTrack?.load(audioURL,item.name);$('audioName').textContent=item.name;$('audioLibrary').value=item.id;changed();status('已载入内置歌曲 · 音频与时间轴同步');}

async function loadAudio(file,ref=null){if(!ref){const id=crypto.randomUUID();await storeFiles(id,[file]);ref={id,name:file.name};}state.audioFile=ref;$('audioLibrary').value='';if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(file);audio.src=audioURL;audioTrack?.load(audioURL,file.name);$('audioName').textContent=file.name;audio.load();changed();status('音频已载入 · 将与时间轴同步');}
async function recordVideo(format='webm'){if(format==='mp4'){await exportOfflineVideo();return;}if(!MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')&&!MediaRecorder.isTypeSupported('video/webm')){toast('浏览器不支持 WebM 录制');return;}if(state.recording){recorder.stop();return;}
 try{await togglePlay(false);state.duration=Math.max(1,Math.min(30000,Math.round(Number($('durationInput').value)||state.duration)));const fps=state.outputFPS,includeAudio=format!=='mp4'||$('mp4IncludeAudio').checked,output=videoSize(state.videoResolution,canvas.width,canvas.height);state.exportAspect=output.width/output.height;state.recording=true;renderer.setPixelRatio(1);renderer.setSize(output.width,output.height,false);camera.aspect=state.exportAspect;camera.updateProjectionMatrix();const stream=canvas.captureStream(fps);if(audioURL&&includeAudio){audioContext??=new AudioContext();await audioContext.resume();audioNode??=audioContext.createMediaElementSource(audio);audioDestination??=audioContext.createMediaStreamDestination();audioNode.disconnect();audioNode.connect(audioContext.destination);audioNode.connect(audioDestination);for(const t of audioDestination.stream.getAudioTracks())stream.addTrack(t);}
  const oldSpeed=state.speed;state.speed=1;audio.playbackRate=1;$('speed').value='1';
  const type=MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')?'video/webm;codecs=vp8,opus':'video/webm';recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:Math.min(100000000,Math.round(output.width*output.height*fps*.15))});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{state.recording=false;restorePreviewSize();$('outputFPS').disabled=false;$('videoResolution').disabled=false;togglePlay(false);state.speed=oldSpeed;$('speed').value=String(oldSpeed);$('recordVideo').textContent='录制预览 WebM';$('recordMP4').textContent='导出预览 MP4';for(const t of stream.getVideoTracks())t.stop();const blob=new Blob(chunks,{type});try{if(format==='mp4'){status('正在本机编码 MP4…');$('recordMP4').disabled=true;const response=await postLocal('/api/render-mp4?fps='+fps+'&audio='+includeAudio,{method:'POST',body:blob});const saved=await response.json();if(!response.ok)throw new Error(saved.error||'MP4 编码失败');const file=await (await fetch(saved.url)).blob();const selected=await download(file,'22-7-preview.mp4','video/mp4');if(selected)toast('MP4 已保存至选定位置 · '+(includeAudio&&audioURL?'包含音频':'无音频'));}else await download(blob,'22-7-preview.webm','video/webm');status('预览视频已导出');}catch(e){fail(e);}finally{$('recordMP4').disabled=false;}};recorder.onerror=e=>{if(recorder.state==='recording')recorder.stop();fail(new Error('录制失败：'+(e.error?.message||'浏览器编码异常')));};state.recording=true;$('outputFPS').disabled=true;$('videoResolution').disabled=true;$('recordVideo').textContent='停止录制并导出';$('recordMP4').textContent='停止录制并导出';setFrame(0);if(audioURL)await new Promise(resolve=>{if(!audio.seeking)return resolve();audio.addEventListener('seeked',resolve,{once:true});setTimeout(resolve,1500);});apply();renderScene($('enableOutline').checked);recorder.start(250);await togglePlay(true);toast('按 '+fps+' fps · '+output.width+'×'+output.height+' 实时录制完整时间轴，再本机导出 '+format.toUpperCase()+'；再次点击可提前结束');
 }catch(e){state.recording=false;restorePreviewSize();$('outputFPS').disabled=false;$('videoResolution').disabled=false;fail(e);}}
async function handleFile(file){try{if(file.name.toLowerCase().endsWith('.vmd')){await storeFiles(crypto.randomUUID(),[file]);await importMotion(await file.arrayBuffer(),file.name);}else if(/\.(json|nana)$/i.test(file.name))await openProject(JSON.parse(await file.text()));else if(file.type.startsWith('audio/')||/\.(mp3|wav|ogg|m4a|flac)$/i.test(file.name))await loadAudio(file);else toast('支持 VMD、工程 JSON 和音频文件');}catch(e){fail(e);}}
async function exportOfflineVideo(){if(state.recording){if(state.offlineExport)state.offlineCancel=true;else if(recorder?.state==='recording')recorder.stop();return;}const previous=state.frame;let dialog=$('videoRenderProgress');try{if(!$('loading').classList.contains('hidden'))throw new Error('请等待模型与舞台载入完成');await togglePlay(false);state.duration=Math.max(1,Math.min(30000,Math.round(Number($('durationInput').value)||state.duration)));const output=videoSize(state.videoResolution,canvas.width,canvas.height),fps=state.outputFPS;state.offlineExport=true;state.offlineCancel=false;state.recording=true;state.exportAspect=output.width/output.height;controls.enabled=false;renderer.setPixelRatio(1);renderer.setSize(output.width,output.height,false);camera.aspect=state.exportAspect;camera.updateProjectionMatrix();$('outputFPS').disabled=true;$('videoResolution').disabled=true;$('recordMP4').textContent='取消逐帧导出';
 if(!dialog){dialog=document.createElement('dialog');dialog.id='videoRenderProgress';dialog.innerHTML='<h2>逐帧导出 MP4</h2><p class="hint">按固定时间渲染每一帧，导出速度由本机性能决定。请保持页面开启。</p><progress id="videoRenderBar" max="1" value="0" style="width:100%"></progress><p id="videoRenderLabel"></p><button id="cancelVideoRender">取消导出</button>';document.body.append(dialog);$('cancelVideoRender').onclick=()=>state.offlineCancel=true;dialog.oncancel=e=>{e.preventDefault();state.offlineCancel=true;};}dialog.showModal();
 state.frame=0;apply();renderer.shadowMap.enabled=ground.visible&&$('enableShadow').checked;await renderer.compileAsync(scene,viewCamera());renderScene($('enableOutline').checked);
 const saved=await exportFrameVideo({canvas,...output,fps,encoder:$('videoEncoder').value,pipeline:Number($('videoPipeline').value),duration:state.duration,audioURL:$('mp4IncludeAudio').checked?audioURL:null,offset:audioTrack?.offset||0,gain:audio.muted?0:audio.volume,cancelled:()=>state.offlineCancel,render:frame=>{state.frame=frame;apply();renderScene($('enableOutline').checked);},progress:(done,total,phase)=>{$('videoRenderBar').value=done/total;$('videoRenderLabel').textContent=phase+' · '+done+' / '+total+' 帧 · '+output.width+'×'+output.height+' · '+fps+' fps';status('MP4 '+phase+' · '+Math.round(done/total*100)+'%');}});dialog.close();state.recording=false;state.offlineExport=false;restorePreviewSize();setFrame(previous);apply();const selected=await download(saved,'22-7-preview.mp4','video/mp4');if(selected)toast('MP4 已逐帧保存 · '+saved.frames+' 帧 · '+fps+' fps · 无实时录制丢帧');status('逐帧 MP4 导出完成');
 }catch(e){if(dialog?.open)dialog.close();if(state.offlineCancel){toast('逐帧导出已取消');status('导出已取消，工程保留');}else fail(e);}finally{state.recording=false;state.offlineExport=false;restorePreviewSize();setFrame(previous);apply();controls.enabled=true;$('outputFPS').disabled=false;$('videoResolution').disabled=false;$('recordMP4').textContent='导出预览 MP4';state.drawPending=true;}}
function restorePreviewSize(){state.exportAspect=null;setPreviewQuality();renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();state.drawPending=true;}
async function newProject(){try{if(state.recording)throw new Error('请先结束录制');await togglePlay(false);const draft=project();const db=await openDB(),tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(draft,'previous-project');await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error);});db.close();$('restorePreviousProject').disabled=false;$('restorePreviousProject').classList.remove('hidden');const profile=state.catalog.characters[0]||{id:'unity-standard',name:'标准 Unity 人形',bodyScale:1,headScale:1};await openProject({format:'nananiji-studio',version:1,renderVersion:7,name:'未命名工程',profile,components:{body:state.catalog.characters.length?'120010100':'unity-standard',face:profile.face||'',hair:profile.hair||'',skin:profile.skin||'',accessory:'',faceAccessory:'',backAccessory:''},variants:{body:'01',accessory:'01',subwear:'01'},motion:emptyClip(),edits:{bones:{},morphs:{}},duration:300,ensemble:{enabled:false,moveEnabled:false,autoPlacement:true,primary:{slot:3,position:[0,0,0],rotation:0},actors:[]},cameraTrack:null,cameraSettings:{aspect:16/9,frameFit:'contain',gameScaling:true,offset:0,projection:'auto',scale:.08,unityScale:1,near:.01,far:200},scene:{background:'#262937',outline:true,shadow:true,cameraMotion:false,light:1,camera:{position:[0,1,-3.6],target:[0,.85,0],fov:35}},background:null,backgroundImage:null,customAccessories:[],backgroundLibrary:[]});state.selection=null;updateInspector();state.frame=0;state.loop=true;state.speed=1;$('speed').value='1';$('loop').setAttribute('aria-pressed','true');$('loop').classList.add('active');$('projectName').textContent='未命名工程';refreshMotion();changed();toast('新工程已创建；上一工程保留为本机恢复副本');}catch(e){fail(e);}}
function bindUI(){fetch('/api/video-capabilities').then(r=>r.json()).then(c=>{$('videoCapabilities').textContent=c.nvenc?'NVIDIA GPU 编码可用':'使用 CPU 编码 · NVIDIA GPU 不可用';$('videoEncoder').querySelector('[value=nvenc]').disabled=!c.nvenc;}).catch(()=>{$('videoCapabilities').textContent='编码器检测失败，可使用 CPU 模式';});$('restorePreviousProject').onclick=async()=>{try{const db=await openDB(),p=await new Promise((r,j)=>{const q=db.transaction('projects').objectStore('projects').get('previous-project');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});db.close();if(p)await openProject(p);else toast('没有可恢复的上一工程');}catch(e){fail(e);}};$('newProject').onclick=newProject;for(const [id,name] of VIDEO_SIZES)$('videoResolution').add(new Option(name,id));$('videoResolution').onchange=()=>{state.videoResolution=$('videoResolution').value;changed();};$('fullscreenPreview').onclick=async()=>{const viewport=canvas.closest('.viewport');try{if(document.fullscreenElement)await document.exitFullscreen();else await viewport.requestFullscreen();}catch{viewport.classList.toggle('expanded-preview');}state.drawPending=true;};document.addEventListener('fullscreenchange',()=>{$('fullscreenPreview').textContent=document.fullscreenElement?'退出全屏':'全屏';state.drawPending=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape'){canvas.closest('.viewport').classList.remove('expanded-preview');state.drawPending=true;}});$('stopService').onclick=async()=>{try{if(state.recording)throw new Error('请先结束录制');await togglePlay(false);await saveLocal();const response=await postLocal('/api/shutdown',{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error);state.serviceStopped=true;$('stopService').disabled=true;$('stopService').textContent='服务已关闭';status('本机服务已关闭；再次运行启动22-7.cmd 可重新打开');toast('当前 22/7 Node.js 服务已关闭，工程已自动保存');}catch(e){fail(e);}};$('outputFPS').onchange=()=>{state.outputFPS=$('outputFPS').value==='30'?30:60;changed();};document.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>switchTab('left',b.dataset.left));document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>switchTab('right',b.dataset.right));$('boneSearch').oninput=renderBones;$('morphSearch').oninput=renderMorphs;
 $('mobileInspector').onclick=()=>document.querySelector('.right-panel').classList.toggle('mobile-visible');
 $('selectHead').onclick=()=>{const b=state.model?.head;if(b){switchTab('left','bones');select({type:'bone',key:b.userData.key});}};
 $('insertKey').onclick=()=>{const b=selectedBone();if(b){pushHistory();writeBoneKey(b);}};$('resetPose').onclick=()=>{const b=selectedBone();if(b){pushHistory();b.quaternion.copy(b.userData.rest.quaternion);b.position.copy(b.userData.rest.position);writeBoneKey(b);}};$('deleteKey').onclick=deleteKey;$('deleteMorphKey').onclick=deleteKey;
 $('morphWeight').oninput=()=>{const m=selectedMorph();if(m){m.mesh.morphTargetInfluences[m.index]=Number($('morphWeight').value);$('morphValue').textContent=Number($('morphWeight').value).toFixed(2);}};$('morphWeight').onchange=()=>{const m=selectedMorph();if(m){pushHistory();writeMorphKey(m);}};$('insertMorphKey').onclick=()=>{const m=selectedMorph();if(m){pushHistory();writeMorphKey(m);}};
 $('play').onclick=()=>togglePlay();$('firstFrame').onclick=()=>setFrame(0);$('prevFrame').onclick=()=>setFrame(Math.round(state.frame)-1);$('nextFrame').onclick=()=>setFrame(Math.round(state.frame)+1);$('frameInput').onfocus=()=>togglePlay(false);$('frameInput').oninput=()=>setFrame($('frameInput').value);$('speed').onchange=()=>{state.speed=Number($('speed').value);audio.playbackRate=state.speed;};$('loop').onclick=()=>{state.loop=!state.loop;$('loop').classList.toggle('active',state.loop);$('loop').setAttribute('aria-pressed',state.loop);};$('durationInput').onchange=$('durationInput').oninput=()=>{pushHistory();state.duration=Math.max(1,Math.min(30000,Math.round(Number($('durationInput').value)||300)));$('durationInput').value=state.duration;setFrame(Math.min(state.frame,state.duration));changed();};$('undo').onclick=undo;$('redo').onclick=redo;
 $('importVMD').onclick=()=>$('vmdFile').click();$('vmdFile').onchange=async()=>{for(const f of $('vmdFile').files)await handleFile(f);$('vmdFile').value='';};$('loadLibraryMotion').onclick=async()=>{const id=$('motionSelect').value,item=state.catalog.motions.find(m=>m.id===id);if(!item){toast('先选择一个动作');return;}try{await togglePlay(false);const r=await fetch('/api/motion/'+id);if(!r.ok)throw new Error('动作文件读取失败');await importMotion(await r.arrayBuffer(),item.name);const song=item.path.split('/')[0],music=state.catalog.motions.find(m=>m.kind==='audio'&&m.path.split('/')[0]===song);if(music)loadAudioLibrary(music);}catch(e){fail(e);}};
 $('newMotion').onclick=()=>{state.motion=emptyClip();state.edits={bones:{},morphs:{}};state.duration=300;state.history=[];state.future=[];$('clipName').textContent='新建动作';$('motionSummary').textContent='新建动作 · 300 帧';$('durationInput').value=300;setFrame(0);updateHistory();report();changed();};
 $('motionScale').onchange=()=>{state.retarget.settings.scale=Math.max(.001,Math.min(1,Number($('motionScale').value)||.08));changed();};$('armAngle').oninput=()=>{state.retarget.settings.armAngle=Number($('armAngle').value);$('armAngleValue').textContent=$('armAngle').value+'°';changed();};$('enableIK').onchange=()=>{state.retarget.settings.ik=$('enableIK').checked;changed();};$('enableRoot').onchange=()=>{state.retarget.settings.rootMotion=$('enableRoot').checked;changed();};
 $('frontView').onclick=()=>{if(state.dirty)apply();const box=new THREE.Box3().setFromObject(state.model.motionRoot),center=box.getCenter(new THREE.Vector3());center.y=.85;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(0,.1,-3.5));camera.fov=35;camera.up.set(0,1,0);camera.updateProjectionMatrix();$('cameraFov').value=35;state.previewCamera=false;controls.update();};$('fitView').onclick=()=>{if(state.dirty)apply();const box=sceneTools?.ensemble.bounds()||new THREE.Box3().setFromObject(state.model.motionRoot);if(box.isEmpty())box.setFromPoints(state.model.bones.map(b=>b.getWorldPosition(new THREE.Vector3())));const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());controls.target.copy(center);camera.fov=35;camera.position.copy(center).add(new THREE.Vector3(0,0,-fitDistance(size,camera.aspect,camera.fov)));camera.up.set(0,1,0);camera.updateProjectionMatrix();$('cameraFov').value=35;state.previewCamera=false;controls.update();changed();};
 for(const id of ['skeletonToggle','gridToggle'])$(id).onclick=()=>{const on=$(id).getAttribute('aria-pressed')!=='true';$(id).setAttribute('aria-pressed',on);$(id).classList.toggle('active',on);if(id==='gridToggle')grid.visible=on&&!state.greenScreen&&!state.background;state.drawPending=true;};
 for(const id of ['lightAzimuth','lightElevation'])$(id).oninput=()=>{updateLight();changed();};$('backgroundColor').oninput=()=>{featureController?.restoreBackgroundImage(null);changed();};$('lightIntensity').oninput=()=>{keyLight.intensity=Number($('lightIntensity').value);previewLight.intensity.value=keyLight.intensity;changed();};$('enableOutline').onchange=changed;$('enableShadow').onchange=()=>{ground.visible=$('enableShadow').checked&&!state.background&&!state.greenScreen;changed();};$('enableCamera').onchange=()=>{camera.up.set(0,1,0);changed();};$('cameraFov').oninput=()=>{camera.fov=Number($('cameraFov').value);camera.updateProjectionMatrix();changed();};
 $('audioFile').onchange=()=>{if($('audioFile').files[0])loadAudio($('audioFile').files[0]).catch(fail);};$('muteAudio').onclick=()=>{audio.muted=!audio.muted;$('muteAudio').setAttribute('aria-pressed',audio.muted);$('muteAudio').classList.toggle('active',audio.muted);};
 $('openProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=()=>{if($('projectFile').files[0])handleFile($('projectFile').files[0]);$('projectFile').value='';};$('saveProject').onclick=async()=>{const saved=await download(JSON.stringify(project()),'22-7-project.nana.json','application/json');if(saved){state.unsaved=false;saveLocal();toast('工程已保存至选定位置；原始动作与编辑关键帧均已包含');}};$('exportMenu').onclick=()=>$('exportOptions').classList.toggle('hidden');document.addEventListener('click',e=>{if(!e.target.closest('.export-wrap'))$('exportOptions').classList.add('hidden');});
 $('exportUnityModel').onclick=async()=>{const previous=state.frame;try{await togglePlay(false);setLoading(true,'正在打包 Unity 模型、贴图与自定义配饰');restoreClothGeometry(state.model);resetBones(state.model.bones);state.model.motionRoot.position.set(0,0,0);state.model.motionRoot.quaternion.identity();state.model.updateAttachments();const bytes=await exportUnityModelPackage(state.model);setLoading(false);await download(bytes,state.profile.name.replace(/[\\/:*?"<>|]/g,'_')+'-Unity.zip','application/zip');status('Unity 模型包已生成，解压到 Unity Assets 后使用随附导入器');}catch(e){fail(e);}finally{setFrame(previous);apply();setLoading(false);}};$('exportGLB').onclick=exportGLB;$('exportNative').onclick=async()=>{try{download(JSON.stringify(toUnityAnimation(await bakeNative(),state.model)),'22-7-unity-animation.json','application/json');status('Unity 左手坐标系骨骼动画已导出');}catch(e){setLoading(false);fail(e);}};$('exportVMD').onclick=exportVMD;$('screenshot').onclick=()=>{renderScene($('enableOutline').checked);canvas.toBlob(b=>download(b,'22-7-preview.png'),'image/png');};$('recordVideo').onclick=()=>recordVideo('webm');$('recordMP4').onclick=()=>recordVideo('mp4');
 document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.code==='Space'){e.preventDefault();togglePlay();}if(e.key==='ArrowLeft'){e.preventDefault();setFrame(Math.round(state.frame)-1);}if(e.key==='ArrowRight'){e.preventDefault();setFrame(Math.round(state.frame)+1);}if(e.key==='Home')setFrame(0);if(e.key==='End')setFrame(state.duration);if(e.key==='Delete'){e.preventDefault();if(e.target.id==='timelineCanvas'||$('tracksPanel').contains(e.target)||e.target.id==='timelineDeleteKey')trackEditor?.remove();else deleteKey();}if(e.key.toLowerCase()==='k'){e.preventDefault();trackEditor?.insert();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('saveProject').click();}if(e.key==='Escape')document.querySelector('.right-panel').classList.remove('mobile-visible');});
 let depth=0;document.addEventListener('dragenter',e=>{e.preventDefault();depth++;$('dropOverlay').classList.remove('hidden');});document.addEventListener('dragleave',e=>{e.preventDefault();if(--depth<=0)$('dropOverlay').classList.add('hidden');});document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',async e=>{e.preventDefault();depth=0;$('dropOverlay').classList.add('hidden');for(const f of e.dataTransfer.files)await handleFile(f);});window.addEventListener('beforeunload',e=>{if(state.unsaved){e.preventDefault();e.returnValue='';}});
}

function updateVariants(){if(!state.catalog)return;for(const family of ['body','accessory']){const select=$(family+'Variant'),item=state.catalog.models.find(m=>m.family===family&&m.id===state.components[family]),variants=[...new Map((item?.variants||[]).map(v=>[v.id,v])).values()];select.replaceChildren();if(!variants.length)select.add(new Option('默认配色','01'));for(const v of variants)select.add(new Option(v.label,v.id));if(![...select.options].some(o=>o.value===state.variants[family]))state.variants[family]=select.options[0]?.value||'01';select.value=state.variants[family];select.onchange=()=>{state.variants[family]=select.value;rebuild(state.retarget?.settings,state.retarget?.mapping,state.retarget?.sourcePositions);};}$('subwearVariant').value=state.variants.subwear;$('subwearVariant').onchange=()=>{state.variants.subwear=$('subwearVariant').value;rebuild(state.retarget?.settings,state.retarget?.mapping,state.retarget?.sourcePositions);};}
function refreshMotion(){trackEditor?.refresh();$('gameMotionSelect').value=state.motion.gameMotion?.id||'';$('clipName').textContent=state.motion.name;$('durationInput').value=state.duration;$('motionSummary').textContent=state.motion.name+' · '+state.duration+' 帧 · 可编辑原生骨骼';drawTimeline();}

async function boot(){try{initRenderer();setupPoseFields();setupTimeline();bindUI();updateHistory();const response=await fetch('/api/catalog');if(!response.ok)throw new Error('本地资源服务不可用');setupCatalog(localizeCatalog(await response.json()));audioTrack=new AudioTimeline(audio,changed,drawTimeline);sceneTools=initSceneTools({state,scene,camera,controls,changed,status,toast,fail,togglePlay,setLoading,refreshMotion,rebuild,syncComponents,updateVariants,fitView:()=>$('fitView').click()});featureController=initFeatures({scene,fitBackground,setBackdrop:loaded=>{grid.visible=!loaded&&$('gridToggle').getAttribute('aria-pressed')==='true';ground.visible=!loaded&&$('enableShadow').checked;},state,rebuild,changed,setFrame,apply,status,fail,toast,download,setLoading,togglePlay,report,pushHistory,refreshMotion,sceneTools,loadAudioLibrary});trackEditor=initTrackEditor({state,sceneTools,changed,drawTimeline,setFrame,togglePlay,pushHistory,toast,fail,apply,switchTab,timelineScale,clearAudio,refreshMotion});appearance=initAppearance({state,scene,featureController,grid,ground,changed,setPreviewQuality,focusSelected:()=>{const head=state.model?.head;if(head){state.rendering??={};const active=viewCamera();active.updateMatrixWorld(true);state.rendering.focus=Math.max(.1,-active.worldToLocal(head.getWorldPosition(new THREE.Vector3())).z);}}});setPreviewQuality();customAccessories=initCustomAccessories({state,changed,fail,toast});const db=await openDB();const previous=await new Promise(resolve=>{const q=db.transaction('projects').objectStore('projects').get('previous-project');q.onsuccess=()=>resolve(q.result);q.onerror=()=>resolve(null);});db.close();$('restorePreviousProject').classList.toggle('hidden',!previous);$('restorePreviousProject').disabled=!previous;const saved=await readLocal();if(saved&&(state.catalog.characters.length||['unity-standard'].includes(saved.components?.body)||saved.components?.body?.startsWith('imported:'))){saved.greenScreen=false;await openProject(saved);}else await rebuild();}catch(e){setLoading(false);fail(e);}}
// Deliberately small inspection API for automated regression tests and debugging.
window.studio={state,setFrame,apply,project,importMotion,bakeNative};
boot();
