import {initCaptureControls,drawCapture} from './capture-controls.mjs';
import {initPhysicsControls} from './physics-controls.mjs';
import {roleSlot} from './core/game-layout.mjs';
import {postLocal} from './core/local-api.mjs';
import {zh} from './core/i18n.mjs';
import { standardUnityModel,autoMap,HUMANOID } from './core/rig.mjs';
import { captureRest } from './core/retarget.mjs';
import { importModel,bakeImportedClip } from './core/imports.mjs';
import { Parser } from './lib/mmdparser.mjs';
import { LocalPoseDetector,PoseSolver,drawPose } from './core/pose.mjs';
import {FaceSolver} from './core/face.mjs';
import { exportPMXPackage } from './core/pmx-export.mjs';
import { emptyClip,linearInterpolation } from './core/vmd.mjs';
import {loadGameMotion} from './core/game-motion.mjs';
import {loadBackground} from './core/background.mjs';
import {loadBuiltinStage} from './core/stage.mjs';
import {TextureLoader,CanvasTexture,SRGBColorSpace,Color} from 'three';
const $=id=>document.getElementById(id);
const imported=new Map();
const persisted=new Set();
async function modelsDB(){return new Promise((resolve,reject)=>{const q=indexedDB.open('nananiji-models',1);q.onupgradeneeded=()=>q.result.createObjectStore('files');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
export async function storeFiles(id,files){
 if(new Set(files.map(f=>f.name.toLowerCase())).size!==files.length)throw new Error('导入文件中有同名文件，请先分别命名');
 if(!persisted.has(id)){for(const file of files){const r=await postLocal('/api/local-asset?id='+encodeURIComponent(id)+'&name='+encodeURIComponent(file.name),{method:'POST',body:file});if(!r.ok)throw new Error((await r.json()).error||'无法保存本地资源');}persisted.add(id);}
 imported.set(id,files);
 // Disk is authoritative; the browser cache is optional and may have a quota.
 try{const db=await modelsDB(),tx=db.transaction('files','readwrite');tx.objectStore('files').put(files.map(f=>({name:f.name,blob:f,type:f.type})),id);await new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error);});db.close();}catch{}
}
export async function getFiles(id){
 if(imported.has(id))return imported.get(id);
 const response=await fetch('/api/local-assets/'+encodeURIComponent(id));
 if(response.ok){const {files}=await response.json();if(files.length){const result=[];for(const f of files){const r=await fetch(f.url);if(!r.ok)throw new Error('本地资源读取失败：'+f.name);result.push(new File([await r.blob()],f.name));}imported.set(id,result);persisted.add(id);return result;}}
 let cached;try{const db=await modelsDB();cached=await new Promise((r,j)=>{const q=db.transaction('files').objectStore('files').get(id);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});db.close();}catch{}
 if(!cached)throw new Error('本地资源文件缺失，请重新选择模型与贴图');const files=cached.map(f=>new File([f.blob],f.name,{type:f.type}));await storeFiles(id,files);return files;
}
export async function resolveExtraModel(key){
 if(key==='unity-standard'){const model=standardUnityModel();captureRest(model.motionRoot,model.bones);model.head=autoMap(model.bones).human.Head;return model;}
 if(key.startsWith('imported:'))return importModel(await getFiles(key.slice(9)));
 return null;
}
export function updateExtraUI(state){$('nativeClip').replaceChildren(new Option('选择自带动画…',''));(state.model.animations||[]).forEach((a,i)=>$('nativeClip').add(new Option(a.name||'动作 '+(i+1),i)));$('loadNativeClip').disabled=!state.model.animations?.length;
 const rig=autoMap(state.model.bodyBones,state.retarget?.mapping||{}),note=rig.missing.length?'缺少必要骨骼：'+rig.missing.join('、'):'已识别标准人形骨架';$('modelInfo').textContent+='\n'+note;
 if(!$('bodySelect').querySelector('option[value="'+CSS.escape(state.components.body)+'"]'))$('bodySelect').add(new Option(state.profile.name,state.components.body));$('bodySelect').value=state.components.body;
}
export function initFeatures(h){const {state,rebuild,changed,setFrame,apply,status,fail,toast,download,setLoading,togglePlay,report}=h;let videoURL,poseDetector,cancelled=false,extracting=false,background,backgroundImage,backgroundGeneration=0,imageGeneration=0,fittedBackground,fitStamp='';const backdropCanvas=document.createElement('canvas');initPhysicsControls(state,changed);const captureUI=initCaptureControls(h);
 $('backgroundName').insertAdjacentHTML('beforebegin','<label class="field">已导入背景<select id="savedBackgrounds"><option value="">选择本地背景…</option></select></label><button id="fitBackground" class="full">适配整个舞台 / 背景</button>');
 function backgroundLibrary(){const old=$('savedBackgrounds').value;$('savedBackgrounds').replaceChildren(new Option('选择本地背景…',''));for(const item of state.backgroundLibrary||[])$('savedBackgrounds').add(new Option(item.name,item.id));$('savedBackgrounds').value=old;}
 $('savedBackgrounds').onchange=async()=>{const item=state.backgroundLibrary?.find(x=>x.id===$('savedBackgrounds').value);if(item)try{await restoreBackground(item);}catch(e){fail(e);}};
 $('fitBackground').onclick=()=>{if(background)h.fitBackground(background.root);else toast('先载入舞台或背景模型');};
 $('backgroundName').insertAdjacentHTML('afterend','<label class="checkbox-field"><input id="backgroundOcclusion" type="checkbox">允许背景遮挡角色</label><div class="hint">默认先画背景、再画角色；开启后按真实三维深度遮挡。可用下方 XYZ 调整舞台位置。</div>');
 const backgroundInput=document.createElement('input');backgroundInput.type='file';backgroundInput.multiple=true;backgroundInput.accept='.glb,.gltf,.bin,.fbx,.obj,.mtl,.pmx,.png,.jpg,.jpeg,.bmp,.tga';backgroundInput.className='hidden';document.body.append(backgroundInput);
 function syncOcclusion(){if(!background)return;state.background.occlusion=$('backgroundOcclusion').checked;background.root.traverse(o=>{o.layers.set(state.background.occlusion?0:1);if(o.isLight)o.layers.enableAll();});changed();}
 $('backgroundOcclusion').onchange=syncOcclusion;
 function syncBackground(){if(!background)return;const s=state.background;const scale=Math.max(.001,Math.min(1000,Number($('backgroundScale').value)||1));s.scale=scale;s.position=['X','Y','Z'].map(axis=>Number($('background'+axis).value)||0);s.rotation=Number($('backgroundRotation').value)||0;background.root.scale.setScalar(scale);background.root.position.fromArray(s.position);background.root.rotation.y=s.rotation*Math.PI/180;changed();}
 async function restoreBackground(s){
  const generation=++backgroundGeneration;if(!s){background?.dispose();background=null;state.background=null;$('backgroundName').textContent='未载入背景模型';$('stageSelect').value='';h.setBackdrop(false);return;}
  const item=s.builtin&&state.catalog.stages?.stages.find(item=>item.id===s.builtin);if(s.builtin&&!item)throw new Error('此原游戏舞台尚未内置');
  const loaded=item?await loadBuiltinStage(item):await loadBackground(await getFiles(s.id));if(generation!==backgroundGeneration){loaded.dispose();return;}
  await restoreBackgroundImage(null);background?.dispose();background=loaded;state.background={...s};h.scene.add(loaded.root);loaded.root.visible=!state.greenScreen;h.setBackdrop(true);backgroundLibrary();
  $('backgroundOcclusion').checked=!!s.occlusion;syncOcclusion();$('backgroundName').textContent=loaded.name+(loaded.missing.length?' · 缺少贴图：'+loaded.missing.join('、'):'');$('stageSelect').value=s.builtin||'';
  $('backgroundScale').value=s.scale??1;['X','Y','Z'].forEach((axis,i)=>$('background'+axis).value=s.position?.[i]||0);$('backgroundRotation').value=s.rotation||0;
  $('stageLights').checked=s.lights!==false;$('stageLightStrength').value=s.lightStrength??.6;loaded.setLights?.($('stageLights').checked,Number($('stageLightStrength').value));loaded.update?.(state.frame/30);syncBackground();
 }
 async function restoreBackgroundImage(selection){
  const generation=++imageGeneration,custom=selection&&typeof selection==='object',item=custom?selection:state.catalog.stages?.backgrounds.find(item=>item.name===selection);
  if(!item){backgroundImage?.dispose();backgroundImage=null;fittedBackground?.dispose();fittedBackground=null;fitStamp='';state.backgroundImage=null;h.scene.background=new Color(state.greenScreen?'#00ff00':$('backgroundColor').value);$('backgroundImageSelect').value='';$('backgroundPreview').classList.add('hidden');h.setBackdrop(!!background||state.greenScreen);return;}
  let url=item.url;if(custom){const files=await getFiles(item.id),file=files.find(f=>f.name===item.name);if(!file)throw new Error('背景图片文件缺失，请重新导入');url=URL.createObjectURL(file);}
  let texture;try{texture=await new TextureLoader().loadAsync(url);}finally{if(custom)URL.revokeObjectURL(url);}
  if(generation!==imageGeneration){texture.dispose();return;}await restoreBackground(null);state.autoGameStage=false;$('autoGameStage').checked=false;
  texture.colorSpace=SRGBColorSpace;backgroundImage?.dispose();backgroundImage=texture;fitStamp='';state.backgroundImage=custom?{id:item.id,name:item.name}:item.name;
  if(custom){const previous=$('backgroundImageSelect').querySelector('option[value="local"]');previous?.remove();$('backgroundImageSelect').add(new Option('已导入 · '+item.name,'local'));}
  $('backgroundImageSelect').value=custom?'local':item.name;$('backgroundPreview').src=custom?'/local-assets/'+item.id+'/'+encodeURIComponent(item.name):item.url;$('backgroundPreview').classList.remove('hidden');h.setBackdrop(true);updateScene(state.frame/30);changed();
 }
 state.autoGameStage??=true;$('stageSelect').closest('label').insertAdjacentHTML('afterend','<label class="checkbox-field"><input id="autoGameStage" type="checkbox">载入歌曲时使用原舞台</label>');$('autoGameStage').checked=state.autoGameStage;$('autoGameStage').onchange=()=>{state.autoGameStage=$('autoGameStage').checked;changed();};const stageItems=(state.catalog.stages?.stages||[]).filter(s=>s.meshes>1);for(const [i,item] of stageItems.entries())$('stageSelect').add(new Option('游戏'+(item.meshes>1?'舞台':'平面场景')+' '+String(i+1).padStart(2,'0')+' · '+item.id,item.id));
 $('loadBuiltinStage').onclick=async()=>{const id=$('stageSelect').value;if(!id)return;try{await togglePlay(false);setLoading(true,'正在载入原游戏舞台与光照');state.autoGameStage=false;$('autoGameStage').checked=false;await restoreBackground({builtin:id,scale:1,position:[0,0,0],rotation:0,lights:true,lightStrength:1});toast('原游戏舞台已载入，可调整摆放与舞台灯光');}catch(e){fail(e);}finally{setLoading(false);}};
 for(const item of state.catalog.stages?.backgrounds||[])$('backgroundImageSelect').add(new Option(item.name.replace('adv_bg_','背景 ').replace('.png',''),item.name));
 $('backgroundImageSelect').onchange=async()=>{try{await togglePlay(false);await restoreBackgroundImage($('backgroundImageSelect').value==='local'?state.backgroundImage:$('backgroundImageSelect').value);changed();}catch(e){fail(e);}};
 const imageInput=document.createElement('input');imageInput.type='file';imageInput.accept='.png,.jpg,.jpeg,.webp,.bmp';imageInput.className='hidden';imageInput.id='backgroundImageFile';document.body.append(imageInput);
 $('importBackgroundImage').onclick=()=>imageInput.click();imageInput.onchange=async()=>{const file=imageInput.files[0];if(!file)return;try{await togglePlay(false);setLoading(true,'正在导入背景图片');const id=crypto.randomUUID();await storeFiles(id,[file]);await restoreBackgroundImage({id,name:file.name});toast('背景图片已替换舞台，并保存到本地资源库');}catch(e){fail(e);}finally{imageInput.value='';setLoading(false);}};
 for(const id of ['stageLights','stageLightStrength'])$(id).oninput=()=>{if(state.background){state.background.lights=$('stageLights').checked;state.background.lightStrength=Number($('stageLightStrength').value);background?.setLights?.(state.background.lights,state.background.lightStrength);changed();}};
 $('importBackground').onclick=()=>backgroundInput.click();backgroundInput.onchange=async()=>{const files=[...backgroundInput.files];if(!files.length)return;try{await togglePlay(false);setLoading(true,'正在载入背景模型');state.autoGameStage=false;$('autoGameStage').checked=false;const id=crypto.randomUUID();await storeFiles(id,files);const item={id,name:files.find(f=>/\.(glb|gltf|fbx|obj|pmx)$/i.test(f.name))?.name||files[0].name,scale:1,position:[0,0,0],rotation:0};state.backgroundLibrary??=[];state.backgroundLibrary.push(item);await restoreBackground(item);$('savedBackgrounds').value=id;h.fitBackground(background.root);toast('背景已保存到本地背景库，可切换和调整摆放');}catch(e){fail(e);}finally{setLoading(false);backgroundInput.value='';}};
 $('clearBackground').onclick=async()=>{await restoreBackground(null);await restoreBackgroundImage(null);changed();};for(const id of ['backgroundScale','backgroundX','backgroundY','backgroundZ','backgroundRotation'])$(id).onchange=syncBackground;
 const gameItems=state.catalog.gameMotions?.motions||[];for(const item of gameItems)$('gameMotionSelect').add(new Option(item.name+' · 位置 '+roleSlot(state.catalog,item.id.split('-')[0],item.slot),item.id));$('gameMotionCount').textContent=new Set(gameItems.map(m=>m.name)).size+' 首 / '+gameItems.length+' 段';
 $('loadGameMotion').onclick=async()=>{const id=$('gameMotionSelect').value;if(!id){toast('先选择原游戏舞蹈与站位');return;}try{await togglePlay(false);setLoading(true,'正在解码原游戏舞蹈');const doc=await loadGameMotion(id);if(!state.model.bodyBones.some(b=>b.name==='BodyPelvis'))throw new Error('原游戏舞蹈需使用内置 22/7 原生模型');h.pushHistory();state.motion=emptyClip();state.motion.name=zh(doc.name)+' · 游戏舞蹈 · 站位 '+roleSlot(state.catalog,doc.id.split('-')[0],doc.slot);state.motion.gameMotion={id:doc.id};state.duration=Math.round(doc.duration*30);state.edits={bones:{},morphs:{}};h.refreshMotion();await h.sceneTools.syncSong();const song=doc.id.split('-')[0],music=state.catalog.motions.find(m=>m.kind==='audio'&&m.songId===song);if(music)h.loadAudioLibrary(music);const stageId=state.catalog.gameLayouts?.[song]?.stageId;if(state.autoGameStage&&stageItems.some(s=>s.id===stageId))await restoreBackground({builtin:stageId,scale:1,position:[0,0,0],rotation:0,lights:true,lightStrength:1});const camera=state.catalog.gameCameras?.cameras.find(c=>c.id===song);if(camera)await h.sceneTools.setTrack({format:'game-camera',id:song,name:camera.name+' · 游戏镜头'});setFrame(0);changed();report();status('已载入 Unity 原生身体与表情轨道');toast('原游戏舞蹈已载入，保留原始骨骼旋转与表情');}catch(e){fail(e);}finally{setLoading(false);}};
 const modelInput=document.createElement('input');modelInput.type='file';modelInput.multiple=true;modelInput.accept='.glb,.gltf,.fbx,.pmx,.bin,.png,.jpg,.jpeg,.bmp,.tga';modelInput.className='hidden';document.body.append(modelInput);
 $('importModel').onclick=()=>modelInput.click();modelInput.onchange=async()=>{const files=[...modelInput.files];if(!files.length)return;try{await togglePlay(false);setLoading(true,'正在识别导入模型');const tested=await importModel(files),id=crypto.randomUUID();tested.dispose();await storeFiles(id,files);imported.set(id,files);state.components.body='imported:'+id;state.edits={bones:{},morphs:{}};state.profile={id,name:files.find(f=>/\.(glb|gltf|fbx|pmx)$/i.test(f.name)).name,bodyScale:1,headScale:1};await rebuild();toast('模型已导入，已自动映射 Unity / MMD 骨骼。缺失关节见转换报告。');}catch(e){setLoading(false);fail(e);}modelInput.value='';};
 $('unityTarget').onclick=async()=>{state.components.body='unity-standard';state.profile={id:'unity-standard',name:'标准 Unity 人形',bodyScale:1,headScale:1};state.edits={bones:{},morphs:{}};await rebuild();};
 $('loadNativeClip').onclick=async()=>{const clip=state.model.animations?.[Number($('nativeClip').value)];if(!clip){toast('请选择一段模型自带动画');return;}try{await togglePlay(false);setLoading(true,'正在烘焙原生动作');const baked=await bakeImportedClip(state.model,clip,p=>status('原生动作烘焙 '+Math.round(p*100)+'%'));state.motion=emptyClip();state.motion.name=clip.name||'原生动画';state.edits=baked.edits;state.duration=baked.duration;h.refreshMotion();setFrame(0);changed();setLoading(false);toast('原生动作已生成可编辑的骨骼关键帧');}catch(e){setLoading(false);fail(e);}};
 $('enableCloth').onchange=()=>{state.retarget.settings.cloth=$('enableCloth').checked;changed();};$('clothMargin').onchange=()=>{state.retarget.settings.clothMargin=Math.max(0,Math.min(.025,Number($('clothMargin').value)||0));changed();};
 $('enableSecondary').onchange=()=>{state.retarget.settings.secondary=$('enableSecondary').checked;changed();};$('secondaryStrength').oninput=()=>{state.retarget.settings.secondaryStrength=Number($('secondaryStrength').value);changed();};
 $('clothInertia').oninput=()=>{state.retarget.settings.clothInertia=Number($('clothInertia').value);changed();};$('clothWind').oninput=()=>{state.retarget.settings.clothWind=Number($('clothWind').value);changed();};
 const reference=document.createElement('input');reference.type='file';reference.accept='.pmx';reference.className='hidden';document.body.append(reference);
 $('sourceRig').onchange=async()=>{try{if($('sourceRig').value==='custom'){reference.click();return;}state.retarget.calibrate(null);changed();report();}catch(e){fail(e);}};
 reference.onchange=async()=>{try{const file=reference.files[0];if(!file){$('sourceRig').value=state.retarget.sourcePositions?'custom':'canonical';return;}await storeFiles(crypto.randomUUID(),[file]);const p=new Parser().parsePmx(await file.arrayBuffer(),false);state.retarget.calibrate(Object.fromEntries(p.bones.map(b=>[b.name,b.position])));changed();toast('已按 '+file.name+' 的实际骨架校准动作');}catch(e){fail(e);}reference.value='';};
 $('exportRig').onclick=()=>{const rig=autoMap(state.model.bodyBones,state.retarget?.mapping||{});download(JSON.stringify({format:'nananiji-humanoid-map',version:1,model:state.profile.name,unityToMMD:HUMANOID,nativeToMMD:state.retarget.mapping,missing:rig.missing,extras:rig.extras,sourcePositions:state.retarget.sourcePositions},null,2),'22-7-bone-map.json','application/json');};
 $('exportPMX').onclick=async()=>{const previous=state.frame;try{await togglePlay(false);setLoading(true,'正在转换 MMD 模型与蒙皮');const rig=autoMap(state.model.bodyBones,state.retarget?.mapping||{});if(rig.missing.length)throw new Error('先补齐必要关节的映射后再转换：'+rig.missing.join('、'));const pose=emptyClip();pose.bones['センター']=[{frame:0,position:[0,0,0],quaternion:[0,0,0,1],interpolation:linearInterpolation()}];state.retarget.apply(pose,0);const name=state.profile.name.replace(/[\\/:*?"<>|]/g,'_'),bytes=await exportPMXPackage(state.model,state.retarget,name,p=>status('MMD 模型打包 '+Math.round(p*100)+'%'));download(bytes,name+'-MMD.zip','application/zip');toast('已导出 PMX、贴图与骨骼映射。已生成服装、头发、配饰的基础刚体与弹簧关节，可在 PMX Editor 微调。');status('MMD 模型转换完成');}catch(e){fail(e);}finally{setFrame(previous);apply();setLoading(false);}};
 $('poseFile').onchange=async()=>{const file=$('poseFile').files[0];if(!file)return;poseDetector?.dispose();poseDetector=null;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(file);$('poseVideo').src=videoURL;$('poseVideo').load();$('poseStatus').textContent=file.name+' · 可以开始提取';};
 $('cancelPose').onclick=()=>{cancelled=true;poseDetector?.dispose();poseDetector=null;};
 const detectorOptions=()=>({mode:$('poseMode').value,model:$('poseQuality').value,delegate:$('poseDelegate').value,...captureUI.options()});let detectorStamp='';
 async function getDetector(){const options=detectorOptions(),stamp=JSON.stringify(options);if(stamp!==detectorStamp){poseDetector?.dispose();poseDetector=new LocalPoseDetector(options);detectorStamp=stamp;}else poseDetector??=new LocalPoseDetector(options);await poseDetector.ready;return poseDetector;}
 $('loadPoseModel').onclick=async()=>{try{for(const id of ['loadPoseModel','extractPose','poseMode','poseQuality','poseDelegate','poseFile','poseHands','posePeople'])$(id).disabled=true;$('poseStatus').textContent='正在初始化本地人体 / 面部模型…';const detector=await getDetector();$('poseStatus').textContent=`本地模型已就绪 · ${detector.info.mode==='face'?'FACE':detector.info.model.toUpperCase()+(detector.info.mode==='combined'?' + FACE':'')+(detector.info.hands?' + HAND':'')} · ${detector.info.delegate} · 无需联网`;toast('所选检测模型已在本机工作线程中加载');}catch(e){poseDetector?.dispose();poseDetector=null;$('poseStatus').textContent='检测模型加载失败：'+e.message;fail(e);}finally{for(const id of ['loadPoseModel','extractPose','poseMode','poseQuality','poseDelegate','poseFile','poseHands','posePeople'])$(id).disabled=false;}};
 $('extractPose').onclick=async()=>{if(extracting)return;const video=$('poseVideo'),mode=$('poseMode').value;if(!videoURL){toast('先选择本地视频');return;}if(!Number.isFinite(video.duration)||!video.videoWidth){toast('视频尚未就绪，请等待加载或换用 MP4 / WebM');return;}const rig=autoMap(state.model.bodyBones,state.retarget?.mapping||{});if(mode!=='face'&&!rig.human.Hips){toast('先映射目标骨架的骨盆 / Hips 关节');return;}if(mode!=='face'&&rig.missing.length)toast('将仅提取模型已有的关节；缺失：'+rig.missing.join('、'));
  const oldFrame=state.frame;try{await togglePlay(false);video.pause();cancelled=false;extracting=true;for(const id of ['extractPose','poseMode','poseQuality','poseDelegate','loadPoseModel','poseFile','poseHands','posePeople'])$(id).disabled=true;$('cancelPose').disabled=false;$('poseProgress').value=0;$('poseStatus').textContent='正在加载本地检测模型…';await getDetector();
   const fps=Number($('poseFPS').value),duration=Math.min(video.duration,1000),options={aspect:video.videoWidth/video.videoHeight,smoothing:Number($('poseSmooth').value),mirror:$('poseMirror').checked,rootMotion:$('poseRoot').checked,mapping:state.retarget.mapping},sessions=captureUI.sessions(mode,options);let detected=0,faces=0,total=Math.floor(duration*fps)+1;
   $('poseOverlay').width=video.videoWidth;$('poseOverlay').height=video.videoHeight;
   for(let i=0;i<total;i++){if(cancelled)break;const t=Math.min(i/fps,Math.max(0,video.duration-.001));if(Math.abs(video.currentTime-t)>.0001)await new Promise((resolve,reject)=>{const seek=()=>{clearTimeout(timer);resolve();},timer=setTimeout(()=>{video.removeEventListener('seeked',seek);reject(new Error('视频解码超时'));},10000);video.addEventListener('seeked',seek,{once:true});video.currentTime=t;});const result=await poseDetector.detect(video,t),frame=Math.round(t*30);
    const people=sessions.update(result,frame);detected=sessions.list.reduce((n,p)=>n+p.detected,0);faces=sessions.list.reduce((n,p)=>n+p.faces,0);
    drawCapture($('poseOverlay'),people);$('poseProgress').value=(i+1)/total;$('poseStatus').textContent=`提取 ${i+1} / ${total} · ${people.length} 人 · 人体 ${detected} 帧 · 面部 ${faces} 帧`;status('本地视频提取 '+Math.round((i+1)/total*100)+'%');await new Promise(r=>setTimeout(r,0));
   }
   if(cancelled){setFrame(oldFrame);return;}if(mode!=='face'&&detected<2)throw new Error('没有检测到足够的人体帧，请使用全身清晰可见的视频');h.pushHistory();const fingers=sessions.commit();if(mode!=='face'){state.motion=emptyClip();state.motion.capture={rootSpace:'hips-local',people:captureUI.options().people,fps};state.motion.name=$('poseFile').files[0].name+' · 视频捕捉';}state.duration=Math.max(mode==='face'?state.duration:0,Math.ceil(duration*30));h.refreshMotion();setFrame(0);changed();report();toast('提取结果已映射到当前模型，可在关键帧面板编辑并保存');$('poseStatus').textContent=`完成 · 人体 ${detected} 帧 · 面部 ${faces} 帧 · 匹配 ${sessions.list.reduce((n,p)=>n+(p.face?.matched.size||0),0)} 条表情 · ${fingers} 条手指轨道。`;
  }catch(e){if(!cancelled)fail(e);setFrame(oldFrame);}finally{extracting=false;for(const id of ['extractPose','poseMode','poseQuality','poseDelegate','loadPoseModel','poseFile','poseHands','posePeople'])$(id).disabled=false;$('cancelPose').disabled=true;if(cancelled)$('poseStatus').textContent='已停止，当前动作未替换';apply();}
 };
 function updateScene(time){background?.update?.(time);if(background)background.root.visible=!state.greenScreen;if(state.greenScreen){h.scene.background=new Color('#00ff00');return;}if(backgroundImage){const canvas=$('viewportCanvas'),w=Math.max(1,state.recording?canvas.width:canvas.clientWidth),height=Math.max(1,state.recording?canvas.height:canvas.clientHeight),fit=state.backgroundFit||'contain',stamp=[w,height,fit,$('backgroundColor').value].join(':');if(stamp!==fitStamp){fitStamp=stamp;backdropCanvas.width=w;backdropCanvas.height=height;const x=backdropCanvas.getContext('2d'),image=backgroundImage.image,scale=fit==='cover'?Math.max(w/image.width,height/image.height):Math.min(w/image.width,height/image.height),dw=fit==='stretch'?w:image.width*scale,dh=fit==='stretch'?height:image.height*scale;x.fillStyle=$('backgroundColor').value;x.fillRect(0,0,w,height);x.drawImage(image,(w-dw)/2,(height-dh)/2,dw,dh);fittedBackground??=new CanvasTexture(backdropCanvas);fittedBackground.colorSpace=SRGBColorSpace;fittedBackground.needsUpdate=true;}h.scene.background=fittedBackground;}else h.scene.background=new Color($('backgroundColor').value);}
 function setGreenScreen(enabled){state.greenScreen=enabled;h.setBackdrop(enabled||!!background||!!backgroundImage);updateScene(state.frame/30);backgroundLibrary();}
 return {backgroundRoot:()=>background?.root,refreshCapture:captureUI.refresh,isExtracting:()=>extracting,restoreBackground,restoreBackgroundImage,updateScene,setGreenScreen};
}
