import {postLocal} from './core/local-api.mjs';
const $=id=>document.getElementById(id);
let busy=false;
export async function saveOutput(data,name,type='application/octet-stream'){
 if(busy)throw new Error('请先完成或取消当前保存');busy=true;
 const serverRef=data?.serverRender?data:null,blob=serverRef?null:data instanceof Blob?data:new Blob([data],{type});let dialog=$('saveOutputDialog');
 if(!dialog){dialog=document.createElement('dialog');dialog.id='saveOutputDialog';dialog.innerHTML='<h2>选择保存位置</h2><p id="saveOutputName"></p><label class="field">本机完整文件路径<input id="saveOutputPath" type="text" spellcheck="false"></label><label class="checkbox-field"><input id="saveOutputOverwrite" type="checkbox">允许覆盖同名文件</label><p class="hint">Chrome 可用“浏览并保存”打开系统文件选择器；也可输入本机完整路径保存。</p><div id="saveOutputError" class="hint"></div><div class="button-row"><button id="saveOutputBrowse">浏览并保存</button><button id="saveOutputLocal" class="primary">按路径保存</button><button id="saveOutputCancel">取消</button></div>';document.body.append(dialog);}
 let base=localStorage.getItem('nananiji-save-folder');if(!base){try{base=(await(await fetch('/api/save-directory')).json()).directory;}catch{base='';}}$('saveOutputName').textContent=name+' · '+((serverRef?.size??blob.size)/1048576).toFixed(2)+' MB';$('saveOutputPath').value=base+name;$('saveOutputOverwrite').checked=false;$('saveOutputError').textContent='';$('saveOutputBrowse').disabled=typeof window.showSaveFilePicker!=='function';dialog.showModal();
 return new Promise(resolve=>{const finish=result=>{dialog.close();busy=false;resolve(result);};dialog.oncancel=e=>{e.preventDefault();finish(null);};$('saveOutputCancel').onclick=()=>finish(null);
  $('saveOutputBrowse').onclick=async()=>{try{const ext=name.split('.').at(-1),handle=await window.showSaveFilePicker({suggestedName:name,types:[{description:name,accept:{[type.includes('/')&&type!=='application/octet-stream'?type:'application/octet-stream']:['.'+ext]}}]}),stream=await handle.createWritable();if(serverRef){const response=await fetch(serverRef.url);if(!response.ok)throw new Error('编码视频读取失败');await response.body.pipeTo(stream);}else{await stream.write(blob);await stream.close();}finish({name:handle.name,url:serverRef?.url||URL.createObjectURL(blob),path:handle.name});}catch(e){if(e.name!=='AbortError')$('saveOutputError').textContent='文件选择器不可用，可使用下方完整路径：'+e.message;}};
  $('saveOutputLocal').onclick=async()=>{const button=$('saveOutputLocal');button.disabled=true;try{const path=$('saveOutputPath').value.trim(),response=await postLocal('/api/save-output?path='+encodeURIComponent(path)+'&overwrite='+$('saveOutputOverwrite').checked+(serverRef?'&render='+encodeURIComponent(serverRef.name):''),{method:'POST',body:blob}),saved=await response.json();if(!response.ok)throw new Error(saved.error);localStorage.setItem('nananiji-save-folder',path.slice(0,path.lastIndexOf('\\')+1));finish(saved);}catch(e){$('saveOutputError').textContent=e.message;}finally{button.disabled=false;}};
 });
}
