import {sourceSlot} from './core/game-layout.mjs';
import {zh} from './core/i18n.mjs';
import * as T from 'three';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {loadGameMotion} from './core/game-motion.mjs';
import {Ensemble} from './core/ensemble.mjs';
import {loadGameCamera,sampleCameraTrack,validateCameraTrack,focalFov} from './core/camera.mjs';
import {parseVMD} from './core/vmd.mjs';
import {storeFiles} from './features.mjs';
const $=id=>document.getElementById(id);
export function initSceneTools(h){
 const {state,camera,controls,scene,changed,toast,fail}=h,ensemble=new Ensemble(scene,state),ortho=new T.OrthographicCamera(),preview=new T.PerspectiveCamera(),gizmo=new TransformControls(camera,document.getElementById('viewportCanvas')),settings={projection:'auto',orthoSize:2,near:.01,far:200,scale:.08,unityScale:1,offset:0,positionOffset:[0,0,0],sensorHeight:24,aspect:16/9,frameFit:'contain',gameScaling:true};let cameraDoc=null,bakedCamera=null;
 $('scenePanel').insertAdjacentHTML('afterbegin',`<div class="section-head"><h2>多人舞台与站位</h2></div>
 <label class="checkbox-field"><input id="enableEnsemble" type="checkbox">允许多个模型同时显示</label><label class="checkbox-field"><input id="enableModelMove" type="checkbox">允许移动模型位置</label>
 <label class="field">舞台模型<select id="actorSelect"></select></label><label class="field">新增角色<select id="actorCharacter"></select></label><label class="field">游戏舞蹈站位<select id="actorSlot">${[1,2,3,4,5].map(n=>`<option value="${n}">${n}</option>`).join('')}</select></label>
 <div class="button-row"><button id="addActor">添加角色</button><button id="removeActor">移除选中</button></div><button id="fiveActors" class="full">五人快速选角与换装</button><div class="hint">主角色固定为站位 3；每位成员可分别选择角色、服装和配饰。</div><div id="actorAppearance"><label class="field">选中角色模型<select id="actorModelCharacter"></select></label><label class="field">选中角色服装<select id="actorCostume"></select></label><label class="field">服装配色<select id="actorCostumeColor"></select></label><label class="field">头饰<select id="actorHeadAccessory"></select></label><label class="field">面饰<select id="actorFaceAccessory"></select></label><label class="field">背饰<select id="actorBackAccessory"></select></label><button id="applyActorAppearance" class="full">更新选中角色模型与服装</button></div>
 <label class="checkbox-field"><input id="autoPlacement" type="checkbox" checked>采用原游戏歌曲站位</label>
 <div class="background-position">${['X','Y','Z'].map(a=>`<label>${a}（米）<input id="actor${a}" type="number" step="0.1" value="0"></label>`).join('')}</div><label class="field">模型朝向 Y（°）<input id="actorRotation" type="number" step="5" value="0"></label><button id="centerActor" class="full">重置选中角色到舞台中心</button><label class="field">位置控件<select id="actorTransformMode"><option value="translate">移动 XYZ</option><option value="rotate">旋转</option></select></label><div class="hint">开启移动后，拖动角色脚下的彩色轴或输入 XYZ。自定义位置会关闭原游戏站位。</div><div id="ensembleInfo" class="diagnostics"></div>
 <div class="section-head"><h2>独立镜头轨道</h2></div><label class="field">镜头库<select id="cameraLibrary"><option value="">选择镜头…</option></select></label><div class="button-row"><button id="loadCamera">载入镜头</button><button id="importCamera">导入镜头</button></div><button id="clearCamera" class="full">清除镜头轨道</button><button id="previewCamera" class="full">预览镜头视角</button><div class="hint">暂停时自由观察；播放、录制或点击预览时使用镜头。拖动画面返回自由观察。</div><div id="cameraName" class="diagnostics">未载入镜头</div>
 <label class="field">镜头画幅<select id="cameraAspect"><option value="1.7777777777777777">原游戏 / MMD · 16:9</option><option value="1.3333333333333333">4:3</option><option value="1">1:1</option><option value="0.5625">9:16</option><option value="0">随预览窗口</option></select></label><label class="field">预览画面适配<select id="cameraFrameFit"><option value="contain">保留原画幅（完整显示）</option><option value="fill">覆盖整个视口（裁切）</option></select></label><label class="checkbox-field"><input id="cameraGameScaling" type="checkbox" checked>原游戏入镜角色身高适配</label><label class="field">镜头时间偏移（秒）<input id="cameraOffset" type="number" step="0.1" value="0"></label><label class="field">MMD 镜头单位（米）<input id="cameraScale" type="number" min="0.001" step="0.001" value="0.08"></label>
 <label class="field">导入 Unity / FBX 单位（米）<input id="cameraUnityScale" type="number" min="0.001" step="0.001" value="1"></label><label class="field">投影<select id="cameraProjection"><option value="auto">跟随镜头 / 透视</option><option value="perspective">透视</option><option value="orthographic">正交</option></select></label><label class="field">正交半高（米）<input id="cameraOrthoSize" type="number" min="0.01" step="0.1" value="2"></label>
 <div class="background-position"><label>近裁剪<input id="cameraNear" type="number" min="0.001" step="0.01" value="0.01"></label><label>远裁剪<input id="cameraFar" type="number" min="1" step="10" value="200"></label></div>
 <div class="background-position"><label>焦距（mm）<input id="cameraFocal" type="number" min="1" value="38"></label><label>传感器高度（mm）<input id="cameraSensor" type="number" min="1" value="24"></label></div>
 <div class="hint">Unity 物理镜头按焦距和传感器适配；MMD 保留视角、距离、插值和投影。镜头与身体动作分别载入。</div>
 <div class="background-position">${['X','Y','Z'].map(a=>`<label>相机 ${a}<input id="cameraPos${a}" type="number" step="0.1"></label>`).join('')}</div><div class="background-position">${['X','Y','Z'].map(a=>`<label>目标 ${a}<input id="cameraTarget${a}" type="number" step="0.1"></label>`).join('')}</div><label class="field">镜头滚转（°）<input id="cameraRoll" type="number" step="1" value="0"></label><button id="applyCameraPose" class="full">应用相机位置与目标</button>
 <div id="cameraInfo" class="diagnostics"></div>`);
 for(const p of state.catalog.characters){$('actorCharacter').add(new Option(p.name,p.id));$('actorModelCharacter').add(new Option(p.name,p.id));}for(const m of state.catalog.models.filter(m=>m.available&&m.family==='body'))$('actorCostume').add(new Option(m.label,m.id));for(const [id,family,kind] of [['actorHeadAccessory','accessory','accessory'],['actorFaceAccessory','accessory','faceAccessory'],['actorBackAccessory','accessory','backAccessory']]){const target=$(id);target.add(new Option('无配饰',''));for(const m of state.catalog.models.filter(m=>m.available&&m.family===family&&m.id.startsWith(kind==='faceAccessory'?'3':kind==='backAccessory'?'4':'2')))target.add(new Option(m.label,m.id));}
 for(const m of state.catalog.motions.filter(m=>m.kind==='vmd'&&/相机|镜头/.test(m.name+' '+m.path)))$('cameraLibrary').add(new Option(m.displayPath||m.path,'vmd:'+m.id));
 for(const c of state.catalog.gameCameras?.cameras||[])$('cameraLibrary').add(new Option(c.name+' · 原游戏镜头','game:'+c.id));
 function selected(){return $('actorSelect').value==='primary'?ensemble.settings.primary:ensemble.actors.find(a=>a.config.id===$('actorSelect').value)?.config;}
 const helper=gizmo.getHelper(),moveAnchor=new T.Group();moveAnchor.name='角色移动控件';scene.add(helper,moveAnchor);gizmo.setSize(.8);
 function selectedGroup(){return $('actorSelect').value==='primary'?ensemble.primary:ensemble.actors.find(a=>a.config.id===$('actorSelect').value)?.group;}
 function currentPosition(){const group=selectedGroup(),root=group?.children[0];return group?group.position.clone().add((root?.position.clone()||new T.Vector3()).applyQuaternion(group.quaternion)):new T.Vector3();}
 function syncGizmo(){const group=selectedGroup();if(!state.modelDragging)moveAnchor.position.copy(currentPosition());if(group&&!state.modelDragging)moveAnchor.quaternion.copy(group.quaternion);moveAnchor.updateMatrixWorld(true);if(ensemble.settings.moveEnabled&&group&&!state.recording&&!state.playing&&!state.previewCamera){gizmo.attach(moveAnchor);gizmo.enabled=true;helper.visible=true;}else{gizmo.detach();gizmo.enabled=false;helper.visible=false;}}
 gizmo.addEventListener('change',()=>{state.drawPending=true;});
 gizmo.addEventListener('dragging-changed',e=>{controls.enabled=!e.value;state.modelDragging=e.value;});
 gizmo.addEventListener('objectChange',()=>{const c=selected(),group=selectedGroup();if(!c||!group)return;ensemble.settings.autoPlacement=false;const delta=moveAnchor.position.clone().sub(currentPosition());c.position=c.position.map((v,i)=>v+delta.getComponent(i));const anchor=currentPosition().add(delta);c.rotation=moveAnchor.rotation.y*180/Math.PI;ensemble.updatePlacement();const correction=anchor.sub(currentPosition());c.position=c.position.map((v,i)=>v+correction.getComponent(i));ensemble.updatePlacement();ui();changed();});
 $('actorTransformMode').onchange=()=>gizmo.setMode($('actorTransformMode').value);
 $('centerActor').onclick=()=>{const c=selected();if(!c)return;ensemble.settings.autoPlacement=false;const travel=selectedGroup()?.children[0]?.position.clone()||new T.Vector3();c.position=travel.negate().toArray();c.rotation=0;ensemble.updatePlacement();ui();changed();toast('选中角色已回到舞台中心');};
 function ui(){const old=$('actorSelect').value;$('actorSelect').replaceChildren(new Option('主角色 · '+(state.profile?.name||''),'primary'));for(const a of ensemble.actors)$('actorSelect').add(new Option(a.config.profile.name+' · 站位 '+a.config.slot,a.config.id));$('actorSelect').value=[...$('actorSelect').options].some(o=>o.value===old)?old:'primary';const c=selected();['X','Y','Z'].forEach((axis,i)=>{$('actor'+axis).value=currentPosition().getComponent(i).toFixed(3);$('actor'+axis).disabled=!ensemble.settings.moveEnabled;});$('actorRotation').value=c?.rotation??0;$('actorRotation').disabled=!ensemble.settings.moveEnabled;$('actorSlot').value=c?.slot||state.motion.gameMotion?.id.split('-')[1]||3;$('removeActor').disabled=$('actorSelect').value==='primary';$('enableEnsemble').checked=ensemble.settings.enabled;$('enableModelMove').checked=ensemble.settings.moveEnabled;$('autoPlacement').checked=ensemble.settings.autoPlacement;$('ensembleInfo').textContent=`${ensemble.settings.enabled?ensemble.actors.length+1:1} 个可见模型 · ${ensemble.settings.autoPlacement?'原游戏队形':'自定义站位'}`;syncGizmo();appearanceUI();}
 function config(p,slot){return {id:crypto.randomUUID(),profile:structuredClone(p),components:{...state.components,face:p.face,hair:p.hair,skin:p.skin},variants:structuredClone(state.variants),slot,position:[(slot-3)*1.2,0,0],rotation:0};}
 async function add(p,slot){if(!/^\d+$/.test(state.components.body))throw new Error('多人组装请先选用内置角色服装');if(ensemble.actors.length>=10)throw new Error('最多同时预览 11 个模型');ensemble.settings.enabled=true;await ensemble.add(config(p,slot));ui();changed();}
 $('addActor').onclick=async()=>{try{await add(state.catalog.characters.find(p=>p.id===$('actorCharacter').value),Number($('actorSlot').value));toast('角色已添加，服装与配饰沿用当前组装');}catch(e){fail(e);}};
 function nativeAppearance(c){const profile=state.catalog.characters.find(p=>p.id===c.character);return {profile:structuredClone(profile),components:{...state.components,body:c.body,face:profile.face,hair:profile.hair,skin:profile.skin,accessory:c.accessory,faceAccessory:c.faceAccessory,backAccessory:c.backAccessory},variants:{...state.variants,body:c.color||'01'}};}
 function colorOptions(select,body,value){const item=state.catalog.models.find(m=>m.family==='body'&&m.id===body),variants=[...new Map((item?.variants||[]).map(v=>[v.id,v])).values()];select.replaceChildren();if(!variants.length)select.add(new Option('默认配色','01'));for(const v of variants)select.add(new Option(v.label,v.id));select.value=[...select.options].some(o=>o.value===value)?value:select.options[0].value;}
 function appearanceUI(){const a=ensemble.actors.find(a=>a.config.id===$('actorSelect').value),c=a?.config||{profile:state.profile,components:state.components,variants:state.variants};$('actorModelCharacter').value=c.profile?.id||state.profile.id;$('actorCostume').value=c.components.body;colorOptions($('actorCostumeColor'),c.components.body,c.variants.body);for(const [id,key] of [['actorHeadAccessory','accessory'],['actorFaceAccessory','faceAccessory'],['actorBackAccessory','backAccessory']])$(id).value=c.components[key]||'';}
 $('actorCostume').onchange=()=>colorOptions($('actorCostumeColor'),$('actorCostume').value,'01');
 $('applyActorAppearance').onclick=async()=>{try{await h.togglePlay(false);h.setLoading(true,'正在更新选中角色');const config=nativeAppearance({character:$('actorModelCharacter').value,body:$('actorCostume').value,color:$('actorCostumeColor').value,accessory:$('actorHeadAccessory').value,faceAccessory:$('actorFaceAccessory').value,backAccessory:$('actorBackAccessory').value});const a=ensemble.actors.find(a=>a.config.id===$('actorSelect').value);if(a)await ensemble.replace(a,config);else{Object.assign(state,config);await h.rebuild(state.retarget?.settings,state.retarget?.mapping,state.retarget?.sourcePositions);h.syncComponents();h.updateVariants();}ui();changed();toast('选中角色已独立换装');}catch(e){fail(e);}finally{h.setLoading(false);}};
 let lineupDialog;
 $('fiveActors').onclick=()=>{if(!state.motion.gameMotion){toast('先载入一首原游戏舞蹈');return;}if(!lineupDialog){lineupDialog=document.createElement('dialog');lineupDialog.id='lineupDialog';lineupDialog.innerHTML='<h2>五人快速选角与换装</h2><p class="hint">第 3 位是主角色。应用后按歌曲原始编队播放，每人服装与配饰独立。</p><div id="lineupRows"></div><div class="button-row"><button id="applyLineup" class="primary">应用五人编队</button><button id="cancelLineup">取消</button></div>';document.body.append(lineupDialog);$('cancelLineup').onclick=()=>lineupDialog.close();$('applyLineup').onclick=async()=>{try{await h.togglePlay(false);h.setLoading(true,'正在组装五人编队');const picks=Array.from({length:5},(_,i)=>({slot:i+1,...nativeAppearance({character:$('lineupCharacter'+(i+1)).value,body:$('lineupBody'+(i+1)).value,color:$('lineupColor'+(i+1)).value,accessory:$('lineupAccessory'+(i+1)).value,faceAccessory:$('lineupFaceAccessory'+(i+1)).value,backAccessory:$('lineupBackAccessory'+(i+1)).value})}));lineupDialog.close();ensemble.clear();const main=picks[2];Object.assign(state,{profile:main.profile,components:main.components,variants:main.variants});state.motion.gameMotion.id=state.motion.gameMotion.id.split('-')[0]+'-'+sourceSlot(state.catalog,state.motion.gameMotion.id.split('-')[0],3);state.motion.gameMotion.roleSlot=3;await loadGameMotion(state.motion.gameMotion.id);state.motion.name=state.motion.name.replace(/站位 \d/,'站位 3');state.edits={bones:{},morphs:{}};await h.rebuild(state.retarget?.settings,state.retarget?.mapping,state.retarget?.sourcePositions);h.syncComponents();h.updateVariants();ensemble.settings.enabled=true;ensemble.settings.autoPlacement=true;for(const pick of picks.filter(p=>p.slot!==3))await ensemble.add({...pick,id:crypto.randomUUID(),position:[0,0,0],rotation:0});await ensemble.syncSong();ui();h.refreshMotion();changed();h.fitView();toast('五人编队已应用 · 主角色位于站位 3');}catch(e){fail(e);}finally{h.setLoading(false);}};}
 $('lineupRows').replaceChildren();for(let slot=1;slot<=5;slot++){const current=slot===3?{profile:state.profile,components:state.components,variants:state.variants}:ensemble.actors.find(a=>a.config.slot===slot)?.config;const row=document.createElement('section');row.className='lineup-row';row.innerHTML='<strong>位置 '+slot+(slot===3?' · 主角色':'')+'</strong>'+[['Character','角色'],['Body','服装'],['Color','配色'],['Accessory','头饰'],['FaceAccessory','面饰'],['BackAccessory','背饰']].map(([key,title])=>'<label>'+title+'<select id="lineup'+key+slot+'"></select></label>').join('');$('lineupRows').append(row);for(const [target,source,value] of [['Character','actorModelCharacter',current?.profile.id||state.catalog.characters[(slot-1)%state.catalog.characters.length].id],['Body','actorCostume',current?.components.body||state.components.body],['Accessory','actorHeadAccessory',current?.components.accessory||''],['FaceAccessory','actorFaceAccessory',current?.components.faceAccessory||''],['BackAccessory','actorBackAccessory',current?.components.backAccessory||'']]){const select=$('lineup'+target+slot);for(const option of $(source).options)select.add(new Option(option.text,option.value));select.value=value;}colorOptions($('lineupColor'+slot),$('lineupBody'+slot).value,current?.variants.body||state.variants.body);$('lineupBody'+slot).onchange=()=>colorOptions($('lineupColor'+slot),$('lineupBody'+slot).value,'01');}lineupDialog.showModal();};
 $('removeActor').onclick=()=>{const a=ensemble.actors.find(a=>a.config.id===$('actorSelect').value);if(a){a.model.dispose();a.group.removeFromParent();ensemble.actors=ensemble.actors.filter(x=>x!==a);ensemble.settings.actors=ensemble.settings.actors.filter(x=>x!==a.config);ui();changed();}};
 $('actorSelect').onchange=ui;
 for(const [id,key] of [['enableEnsemble','enabled'],['enableModelMove','moveEnabled'],['autoPlacement','autoPlacement']])$(id).onchange=async()=>{ensemble.settings[key]=$(id).checked;if(key==='autoPlacement'||key==='enabled')await ensemble.syncSong();h.refreshMotion();ensemble.updatePlacement();ui();changed();};
 for(const id of ['actorX','actorY','actorZ','actorRotation'])$(id).oninput=()=>{if(!ensemble.settings.moveEnabled)return;const c=selected();if(!c)return;ensemble.settings.autoPlacement=false;const next=new T.Vector3().fromArray(['X','Y','Z'].map(a=>Number($('actor'+a).value)||0)),delta=next.sub(currentPosition());c.position=c.position.map((v,i)=>v+delta.getComponent(i));const anchor=next.add(currentPosition());c.rotation=Number($('actorRotation').value)||0;ensemble.updatePlacement();const correction=anchor.sub(currentPosition());c.position=c.position.map((v,i)=>v+correction.getComponent(i));ensemble.updatePlacement();$('autoPlacement').checked=false;changed();};
 $('actorSlot').onchange=async()=>{const c=selected();if(c&&c!==ensemble.settings.primary){c.slot=Number($('actorSlot').value);await ensemble.syncSong();ui();changed();}};
 async function setTrack(track){const loaded=track?.format==='game-camera'?await loadGameCamera(track.id):track;state.cameraTrack=track;cameraDoc=loaded;bakedCamera=null;$('cameraName').textContent=zh(track?.name)||'未载入镜头';$('enableCamera').checked=!!track;if(track&&!state.restoring){const duration=cameraDoc.duration??((cameraDoc.keys?.at(-1)?.frame||0)/30);state.duration=Math.max(state.duration,Math.ceil(duration*30));h.refreshMotion();}h.status?.(track?'独立镜头已载入 · 身体动作保留':'独立镜头轨道已清除');changed();}
 const input=document.createElement('input');input.type='file';input.accept='.vmd,.json,.fbx,.glb,.gltf';input.className='hidden';input.id='cameraFile';document.body.append(input);
 $('importCamera').onclick=()=>input.click();input.onchange=async()=>{const file=input.files[0];if(!file)return;try{let track;if(/\.vmd$/i.test(file.name)){const clip=parseVMD(await file.arrayBuffer(),file.name);if(!clip.cameras.length)throw new Error('此 VMD 没有镜头轨道');track={format:'mmd-camera',name:file.name,keys:clip.cameras};}else if(/\.json$/i.test(file.name))track=validateCameraTrack(JSON.parse(await file.text()));else{const {importCameraAnimation}=await import('./core/camera-import.mjs');track=await importCameraAnimation(file);}await storeFiles(crypto.randomUUID(),[file]);await setTrack(track);toast('镜头已单独载入，当前身体动作保留');}catch(e){fail(e);}finally{input.value='';}};
 $('loadCamera').onclick=async()=>{try{const value=$('cameraLibrary').value;if(value.startsWith('game:'))await setTrack({format:'game-camera',id:value.slice(5),name:$('cameraLibrary').selectedOptions[0].text});else if(value.startsWith('vmd:')){const r=await fetch('/api/motion/'+value.slice(4)),clip=parseVMD(await r.arrayBuffer());if(!clip.cameras.length)throw new Error('该文件没有镜头');await setTrack({format:'mmd-camera',name:$('cameraLibrary').selectedOptions[0].text,keys:clip.cameras});}else return;toast('独立镜头已载入');}catch(e){fail(e);}};
 $('clearCamera').onclick=()=>setTrack(null);
 $('previewCamera').onclick=()=>{state.previewCamera=!state.previewCamera;if(state.previewCamera&&cameraDoc)$('enableCamera').checked=true;changed();};
 controls.addEventListener('start',()=>{if(!state.recording){state.previewCamera=false;if(state.playing)h.togglePlay(false);}});
 for(const [id,key] of [['cameraAspect','aspect'],['cameraOffset','offset'],['cameraScale','scale'],['cameraUnityScale','unityScale'],['cameraNear','near'],['cameraFar','far'],['cameraOrthoSize','orthoSize'],['cameraSensor','sensorHeight']])$(id).onchange=()=>{settings[key]=Math.max(key==='offset'?-10000:key==='aspect'?0:.001,Number($(id).value)||(key==='aspect'?0:.001));settings.far=Math.max(settings.near+.01,settings.far);changed();};
 $('cameraFrameFit').onchange=()=>{settings.frameFit=$('cameraFrameFit').value;changed();};$('cameraGameScaling').onchange=()=>{settings.gameScaling=$('cameraGameScaling').checked;bakedCamera=null;changed();};
 $('cameraProjection').onchange=()=>{settings.projection=$('cameraProjection').value;changed();};$('cameraFocal').onchange=()=>{camera.fov=focalFov(Number($('cameraFocal').value),settings.sensorHeight);$('cameraFov').value=camera.fov;camera.updateProjectionMatrix();changed();};
 $('applyCameraPose').onclick=()=>{camera.position.fromArray(['X','Y','Z'].map(a=>Number($('cameraPos'+a).value)||0));controls.target.fromArray(['X','Y','Z'].map(a=>Number($('cameraTarget'+a).value)||0));camera.up.set(0,1,0);camera.lookAt(controls.target);camera.rotateZ(Number($('cameraRoll').value)*Math.PI/180);camera.up.set(0,1,0).applyQuaternion(camera.quaternion);state.previewCamera=false;controls.update();changed();};
 function update(){ensemble.update(state.frame);syncGizmo();if(!document.activeElement?.id?.startsWith('actor'))for(const [i,axis] of ['X','Y','Z'].entries())$('actor'+axis).value=currentPosition().getComponent(i).toFixed(3);camera.near=settings.near;camera.far=settings.far;camera.updateProjectionMatrix();}
 function samplePreview(frame=state.frame){const p=cameraDoc&&sampleCameraTrack(cameraDoc,frame-settings.offset*30,settings.scale,state.recording?state.exportAspect:(settings.frameFit==='fill'?camera.aspect:settings.aspect||camera.aspect),settings.gameScaling?ensemble.scales():{});if(p&&cameraDoc.format==='nananiji-camera'){p.position.multiplyScalar(settings.unityScale);p.orthographicSize*=settings.unityScale;}return p;}
 function cameraKeyframes(){if(state.cameraTrack?.format!=='game-camera')return state.cameraTrack?.keys||[];if(bakedCamera)return bakedCamera;bakedCamera=[];for(let frame=0;frame<cameraDoc.frames;frame++){const p=sampleCameraTrack(cameraDoc,frame,settings.scale,settings.aspect||16/9,settings.gameScaling?ensemble.scales():{});const previous=bakedCamera.at(-1),cut=!!previous&&(p.position.distanceTo(new T.Vector3().fromArray(previous.position))>.7||p.quaternion.angleTo(new T.Quaternion().fromArray(previous.quaternion))>.6);bakedCamera.push({frame,cut,position:p.position.toArray(),quaternion:p.quaternion.toArray(),fov:p.fov,orthographic:p.orthographic,orthographicSize:p.orthographicSize,near:p.near,far:p.far});}return bakedCamera;}
 async function editableCamera(){if(state.cameraTrack?.format==='game-camera'){const keys=structuredClone(cameraKeyframes());settings.unityScale=1;$('cameraUnityScale').value=1;await setTrack({format:'nananiji-camera',coordinates:'three',name:state.cameraTrack.name+' · 已编辑',keys});}return state.cameraTrack;}

 let lastUI=0;function renderCamera(){const active=!!cameraDoc&&$('enableCamera').checked&&(state.playing||state.recording||state.previewCamera),p=active?samplePreview():null,source=p?preview:camera;if(p){preview.position.copy(p.position);preview.quaternion.copy(p.quaternion);preview.up.set(0,1,0).applyQuaternion(p.quaternion);preview.fov=T.MathUtils.clamp(p.fov,1,175);preview.aspect=state.recording?state.exportAspect:settings.frameFit==='fill'?camera.aspect:settings.aspect||camera.aspect;preview.near=settings.near;preview.far=settings.far;preview.updateProjectionMatrix();}
  const on=settings.projection==='orthographic'||settings.projection==='auto'&&p?.orthographic,size=settings.projection==='auto'?p?.orthographicSize||settings.orthoSize:settings.orthoSize;
  ortho.position.copy(source.position);ortho.quaternion.copy(source.quaternion);ortho.left=-size*(active?(state.recording?state.exportAspect:settings.frameFit==='fill'?camera.aspect:settings.aspect||camera.aspect):camera.aspect);ortho.right=-ortho.left;ortho.top=size;ortho.bottom=-size;ortho.near=settings.near;ortho.far=settings.far;ortho.updateProjectionMatrix();
  if(performance.now()-lastUI>250){lastUI=performance.now();if(!document.activeElement?.id?.startsWith('camera'))['X','Y','Z'].forEach((a,i)=>{for(const [prefix,v] of [['cameraPos',camera.position],['cameraTarget',controls.target]])$(prefix+a).value=v.getComponent(i).toFixed(3);});$('previewCamera').textContent=state.previewCamera?'返回自由观察':'预览镜头视角';$('cameraInfo').textContent=`${active?'镜头预览':'自由观察'} · ${on?'正交':'透视'} · 视角 ${source.fov.toFixed(2)}° · 镜头帧 ${Math.round(state.frame-settings.offset*30)}`;}
  state.cameraViewAspect=active?(state.recording?state.exportAspect:settings.frameFit==='fill'?0:settings.aspect):0;return on?ortho:source;
 }
 ui();return {ensemble,setTrack,editableCamera,cameraKeyframes,samplePreview,update,renderCamera,timelineCamera:()=>({offset:settings.offset,duration:cameraDoc?.duration??0}),attach:model=>{ensemble.attach(model);ui();},syncSong:async()=>{await ensemble.syncSong();ui();h.refreshMotion();},save:()=>({ensemble:ensemble.save(),cameraSettings:{...settings},cameraTrack:state.cameraTrack}),restore:async p=>{Object.assign(settings,p.cameraSettings||{});await ensemble.restore(p.ensemble);await setTrack(p.cameraTrack||(p.motion.cameras?.length?{format:'mmd-camera',name:'工程镜头',keys:p.motion.cameras}:null));for(const [id,key] of [['cameraAspect','aspect'],['cameraOffset','offset'],['cameraScale','scale'],['cameraUnityScale','unityScale'],['cameraNear','near'],['cameraFar','far'],['cameraOrthoSize','orthoSize'],['cameraSensor','sensorHeight']])$(id).value=settings[key];$('cameraProjection').value=settings.projection;$('cameraFrameFit').value=settings.frameFit;$('cameraGameScaling').checked=settings.gameScaling;ui();}};
}
