import * as T from 'three';
import {getGameMotion} from './core/game-motion.mjs';
import {nativeBoneKeys,nativeMorphKeys,moveKey,clearClipTracks} from './core/track-edit.mjs';
import {linearInterpolation} from './core/vmd.mjs';
import {MORPH_MAPPING} from './core/retarget.mjs';
const $=id=>document.getElementById(id);
export function initTrackEditor(h){
 const {state,sceneTools,changed,drawTimeline,setFrame,togglePlay,pushHistory,toast}=h;
 let kind='motion',channel='',selection=null,keysCache=new WeakMap();
 document.querySelector('.right-panel .panel-tabs').insertAdjacentHTML('beforeend','<button data-right="tracks">轨道</button>');
 document.querySelector('.right-panel').insertAdjacentHTML('beforeend',`<div id="tracksPanel" class="side-content hidden"><div class="section-head"><h2>轨道清除</h2></div><div class="clear-track-grid"><button id="clearBodyTrack">清除动作</button><button id="clearMorphTrack">清除表情</button><button id="clearCameraTrack">清除相机</button><button id="clearAudioTrack">清除音频</button><button id="clearEditTracks">清除手动修改</button><button id="clearAllTracks">一键清除全部</button></div>
 <label class="field">时间轴总帧数<input id="trackDuration" type="number" min="1" max="30000" step="1" value="300"></label><label class="field">时间轴缩放<input id="trackZoom" type="range" min=".05" max="12" step=".05" value="3"></label><div class="section-head"><h2>关键帧编辑</h2></div><label class="field">编辑角色<select id="editActor"></select></label><label class="field">轨道类型<select id="editTrackKind"><option value="motion">身体 / 骨骼</option><option value="morph">表情</option><option value="camera">相机</option><option value="edit">当前选择</option></select></label><label class="field">通道<select id="editChannel"></select></label><label class="field">通道关键帧<select id="editKeyList"></select></label><div class="button-row"><button id="prevKeyframe">上一关键帧</button><button id="nextKeyframe">下一关键帧</button></div><label class="field">关键帧位置（30 fps）<input id="keyFrame" type="number" min="0" step="1" value="0"></label><div id="keyValueFields"></div><div class="button-row"><button id="addTrackKey">插入当前帧</button><button id="deleteTrackKey">删除选中帧</button></div><button id="applyTrackKey" class="full primary">应用关键帧修改</button><button id="saveTrackProject" class="full">保存工程与全部轨道</button><div id="keyEditInfo" class="hint">点击下方轨道选择通道；拖动菱形移动关键帧，双击轨道插入，Delete 删除，K 插入。内置动画可以直接修改，保存工程后可再次打开。</div></div>`);
 function owner(){const a=sceneTools.ensemble.actors.find(a=>a.config.id===$('editActor').value);if(a){a.config.edits??={bones:{},morphs:{}};return {model:a.model,retarget:a.retarget,motion:state.motion.gameMotion?a.clip:state.motion,edits:a.config.edits};}return {model:state.model,retarget:state.retarget,motion:state.motion,edits:state.edits};}
 function open(){h.switchTab('right','tracks');if(innerWidth<800)document.querySelector('.right-panel').classList.add('mobile-visible');}
 function refresh(){if(!state.model)return;$('trackDuration').value=state.duration;$('trackZoom').value=$('timelineZoom').value;const actor=$('editActor').value;$('editActor').replaceChildren(new Option('主角色 · '+state.profile.name,'primary'));for(const a of sceneTools.ensemble.actors)$('editActor').add(new Option(a.config.profile.name+' · 站位 '+a.config.slot,a.config.id));$('editActor').value=[...$('editActor').options].some(o=>o.value===actor)?actor:'primary';const old=channel,o=owner(),list=$('editChannel');list.replaceChildren();
  if(kind==='camera')list.add(new Option(state.cameraTrack?.name||'相机轨道','camera'));
  else if(kind==='edit'&&state.selection)list.add(new Option(state.selection.key,state.selection.key));
  else if(kind==='morph'){for(const m of o.model.morphs)list.add(new Option(m.name,m.key));for(const name of Object.keys(o.motion.morphs))if(!o.model.morphs.some(m=>m.name===name||m.name.endsWith('BS_'+MORPH_MAPPING[name])))list.add(new Option(name,'vmd:'+name));}
  else{for(const b of o.model.bones)list.add(new Option(b.name+' · '+b.userData.family,b.userData.key));for(const name of Object.keys(o.motion.bones))if(!Object.values(o.retarget.mapping).includes(name))list.add(new Option(name,'vmd:'+name));}
  channel=[...list.options].some(o=>o.value===old)?old:kind==='motion'&&[...list.options].some(o=>o.value==='body/BodyPelvis')?'body/BodyPelvis':list.options[0]?.value||'';list.value=channel;selection=null;refreshKeys();
 }
 function descriptor(k=kind){const o=owner(),doc=getGameMotion(o.motion.gameMotion?.id);if(k==='camera')return {type:'camera',keys:sceneTools.cameraKeyframes(),format:state.cameraTrack?.format==='game-camera'?'nananiji-camera':state.cameraTrack?.format,offset:sceneTools.timelineCamera().offset*30};
  const type=k==='morph'||k==='edit'&&state.selection?.type==='morph'?'morph':'bone',dict=type==='bone'?o.edits.bones:o.edits.morphs,key=k==='edit'?state.selection?.key:channel;
  if(!key)return {type,keys:[]};
  if(Object.hasOwn(dict,key))return {type,keys:dict[key],native:true,key,dict,o};
  const target=type==='bone'?o.model.bones.find(b=>b.userData.key===key):o.model.morphs.find(m=>m.key===key);
  if(doc&&target&&!state.motion[type==='bone'?'disabledBody':'disabledFace']){let cached=keysCache.get(doc);if(!cached){cached=new Map();keysCache.set(doc,cached);}if(!cached.has(key+':'+(o.model.profile?.bodyScale||1)))cached.set(key+':'+(o.model.profile?.bodyScale||1),type==='bone'?nativeBoneKeys(doc,target,o.model.profile?.bodyScale||1):nativeMorphKeys(doc,target));return {type,keys:cached.get(key+':'+(o.model.profile?.bodyScale||1)),native:true,key,dict,o,materialize:true};}
  const name=key.startsWith('vmd:')?key.slice(4):type==='bone'?o.retarget.mapping[target?.name]:Object.keys(o.motion.morphs).find(n=>target?.name===n||target?.name.endsWith('BS_'+MORPH_MAPPING[n]));return {type,keys:(type==='bone'?o.motion.bones:o.motion.morphs)[name]||[],name,target,o,key,dict};
 }
 async function editable(){if(kind==='camera'&&state.cameraTrack?.format==='game-camera')await sceneTools.editableCamera();const d=descriptor();if(d.materialize){d.dict[d.key]=structuredClone(d.keys);return descriptor();}return d;}
 function refreshKeys(){const d=descriptor();$('editKeyList').replaceChildren();for(const key of d.keys)$('editKeyList').add(new Option(String(key.frame)+(d.type==='morph'?' · '+key.weight.toFixed(2):''),String(key.frame)));if(d.keys.length){const frame=selection?.frame??state.frame-(d.offset||0),nearest=d.keys.reduce((a,b)=>Math.abs(a.frame-frame)<Math.abs(b.frame-frame)?a:b);selection=nearest;$('editKeyList').value=String(nearest.frame);}else selection=null;fields();$('keyEditInfo').textContent=`${d.keys.length} 个关键帧 · ${d.native?'Unity 原生 / 编辑':d.type==='camera'?state.cameraTrack?.format||'未载入':'MMD'}。修改内置内容会存入工程。`;
 }
 function fields(){const d=descriptor(),k=selection;const area=$('keyValueFields');area.replaceChildren();$('keyFrame').value=k?.frame??Math.round(state.frame-(d.offset||0));if(!k)return;
  const entries=[];if(k.position)entries.push(['position','位置',k.position]);if(k.quaternion)entries.push(['rotation','旋转（°）',new T.Euler().setFromQuaternion(new T.Quaternion().fromArray(k.quaternion),'XYZ').toArray().slice(0,3).map(v=>v*180/Math.PI)]);else if(k.rotation)entries.push(['rotation','旋转（°）',k.rotation.map(v=>v*180/Math.PI)]);if(k.scale)entries.push(['scale','缩放',k.scale]);for(const [name,label,v] of entries){const row=document.createElement('div');row.className='background-position';v.forEach((n,i)=>{const field=document.createElement('label');field.textContent=label+' '+['X','Y','Z'][i];const input=document.createElement('input');input.type='number';input.step=name==='rotation'?'1':'.01';input.id='key-'+name+'-'+i;input.value=Number(n).toFixed(5);field.append(input);row.append(field);});area.append(row);}
  for(const [name,label] of [['weight','表情权重（0–1）'],['fov','视角（°）'],['distance','MMD 镜头距离'],['orthographicSize','正交半高']])if(k[name]!==undefined){const l=document.createElement('label');l.className='field';l.textContent=label;const i=document.createElement('input');i.type='number';i.step='.01';i.id='key-'+name;i.value=k[name];l.append(i);area.append(l);}
  if(d.type==='camera'){area.insertAdjacentHTML('beforeend',`<label class="checkbox-field"><input id="keyOrthographic" type="checkbox" ${(k.orthographic||k.perspective===1)?'checked':''}>正交镜头</label><label class="checkbox-field"><input id="keyCut" type="checkbox" ${k.cut?'checked':''}>此帧硬切</label>`);}
 }
 function commit(){changed();drawTimeline();refreshKeys();}
 $('editActor').onchange=()=>{selection=null;refresh();drawTimeline();};$('editTrackKind').onchange=()=>{kind=$('editTrackKind').value;channel='';refresh();drawTimeline();};$('editChannel').onchange=()=>{channel=$('editChannel').value;selection=null;refreshKeys();drawTimeline();};$('editKeyList').onchange=()=>{selection=descriptor().keys.find(k=>String(k.frame)===$('editKeyList').value);if(selection){setFrame(selection.frame+(descriptor().offset||0));fields();}};
 for(const [id,delta] of [['prevKeyframe',-1],['nextKeyframe',1]])$(id).onclick=()=>{const d=descriptor(),frame=state.frame-(d.offset||0),key=delta<0?d.keys.filter(k=>k.frame<frame).at(-1):d.keys.find(k=>k.frame>frame);if(key){selection=key;setFrame(key.frame+(d.offset||0));refreshKeys();}};
 $('applyTrackKey').onclick=async()=>{try{const oldFrame=selection?.frame??Number($('keyFrame').value),values={frame:Number($('keyFrame').value)};for(const name of ['position','rotation','scale'])if($('key-'+name+'-0'))values[name]=[0,1,2].map(i=>Number($('key-'+name+'-'+i).value));for(const name of ['weight','fov','distance','orthographicSize'])if($('key-'+name))values[name]=Number($('key-'+name).value);if(!Object.values(values).flat().every(Number.isFinite)||values.frame<0)throw new Error('请输入有效的关键帧数值');if(values.fov!==undefined&&(values.fov<1||values.fov>175))throw new Error('相机视角须在 1–175°');pushHistory();const d=await editable(),key=d.keys.find(k=>k.frame===oldFrame);if(!key)throw new Error('先选择或插入一个关键帧');if(values.position)key.position=values.position;if(values.rotation){const radians=values.rotation.map(v=>v*Math.PI/180);if(key.quaternion)key.quaternion=new T.Quaternion().setFromEuler(new T.Euler(...radians,'XYZ')).toArray();else key.rotation=radians;}if(values.scale)key.scale=values.scale;for(const name of ['weight','fov','distance','orthographicSize'])if(values[name]!==undefined)key[name]=name==='weight'?T.MathUtils.clamp(values[name],0,1):values[name];if(d.type==='camera'){if(key.perspective!==undefined)key.perspective=$('keyOrthographic').checked?1:0;else key.orthographic=$('keyOrthographic').checked;key.cut=$('keyCut').checked;}moveKey(d.keys,key,values.frame);selection=key;state.duration=Math.max(state.duration,key.frame+(d.offset||0));setFrame(key.frame+(d.offset||0));commit();toast('关键帧已修改，可保存工程');}catch(e){h.fail(e);}};
 $('addTrackKey').onclick=async()=>{try{pushHistory();h.apply();const d=await editable(),frame=Math.max(0,Math.round(state.frame-(d.offset||0)));let key=d.keys.find(k=>k.frame===frame);if(!key){if(d.type==='camera'){const pose=sceneTools.samplePreview();if(!pose)throw new Error('先载入镜头轨道');if(d.format==='mmd-camera'){const nearest=d.keys.reduce((a,b)=>Math.abs(a.frame-frame)<Math.abs(b.frame-frame)?a:b);key={...structuredClone(nearest),frame};}else key={frame,position:pose.position.toArray(),quaternion:pose.quaternion.toArray(),fov:pose.fov,orthographic:pose.orthographic,orthographicSize:pose.orthographicSize};}else if(d.native||!d.name){const o=owner();if(d.type==='bone'){const b=o.model.bones.find(b=>b.userData.key===d.key);if(!b)throw new Error('请选择骨骼通道');key={frame,position:b.position.toArray(),quaternion:b.quaternion.toArray(),scale:b.scale.toArray(),curve:[20,20,107,107]};}else{const m=o.model.morphs.find(m=>m.key===d.key);if(!m)throw new Error('请选择表情通道');key={frame,weight:m.mesh.morphTargetInfluences[m.index]};}if(!Object.hasOwn(d.dict,d.key))d.dict[d.key]=d.keys;}else key=d.type==='bone'?{frame,position:[0,0,0],quaternion:[0,0,0,1],interpolation:linearInterpolation()}:{frame,weight:0};d.keys.push(key);moveKey(d.keys,key,frame);}selection=key;commit();}catch(e){h.fail(e);}};
 $('deleteTrackKey').onclick=async()=>{const frame=selection?.frame;if(frame===undefined)return;pushHistory();const d=await editable(),i=d.keys.findIndex(k=>k.frame===frame);if(i>=0)d.keys.splice(i,1);selection=null;commit();};
 async function clear(kind){await togglePlay(false);pushHistory();if(kind==='body'||kind==='morph'||kind==='all'){clearClipTracks(state.motion,state.edits,kind);for(const a of sceneTools.ensemble.actors)clearClipTracks(a.clip,a.config.edits??={bones:{},morphs:{}},kind);}if(kind==='camera'||kind==='all')await sceneTools.setTrack(null);if(kind==='audio'||kind==='all')h.clearAudio();if(kind==='edit'){state.edits={bones:{},morphs:{}};for(const a of sceneTools.ensemble.actors)a.config.edits={bones:{},morphs:{}};}if(kind==='all'){state.duration=300;delete state.motion.gameMotion;state.motion.name='新建动作';state.previewCamera=false;setFrame(0);}keysCache=new WeakMap();h.refreshMotion();refresh();commit();toast(kind==='all'?'所有轨道已清除':'选中轨道已清除');}
 for(const [id,k] of [['clearBodyTrack','body'],['clearMorphTrack','morph'],['clearCameraTrack','camera'],['clearAudioTrack','audio'],['clearEditTracks','edit'],['clearAllTracks','all']])$(id).onclick=()=>clear(k).catch(h.fail);
 $('saveTrackProject').onclick=()=>$('saveProject').click();document.querySelector('[data-right=tracks]').onclick=()=>{open();refresh();};
 document.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{kind=b.dataset.track==='audio'?'motion':b.dataset.track;$('editTrackKind').value=kind;open();refresh();drawTimeline();});
 function rows(){const all=[Object.values(state.motion.bones).flat(),Object.values(state.motion.morphs).flat(),(state.cameraTrack?.keys||[]).map(k=>({frame:k.frame+sceneTools.timelineCamera().offset*30,key:k})),[]];if(state.selection){all[3]=(state.selection.type==='bone'?state.edits.bones:state.edits.morphs)[state.selection.key]||[];}if(channel){const d=descriptor();const row=kind==='motion'?0:kind==='morph'?1:kind==='camera'?2:3;all[row]=d.keys.map(k=>({frame:k.frame+(d.offset||0),key:k}));}return all;}
 async function choose(row,frame){kind=['motion','morph','camera','edit'][row];$('editTrackKind').value=kind;open();refresh();const d=descriptor(),candidate=d.keys.reduce((best,key)=>!best||Math.abs(key.frame+(d.offset||0)-frame)<Math.abs(best.frame+(d.offset||0)-frame)?key:best,null);if(!candidate||Math.abs(candidate.frame+(d.offset||0)-frame)*h.timelineScale()>7)return null;const targetFrame=candidate.frame;pushHistory();const editableTrack=await editable();selection=editableTrack.keys.find(k=>k.frame===targetFrame);refreshKeys();return {key:selection,keys:editableTrack.keys,offset:editableTrack.offset||0};}
 $('trackDuration').onchange=$('trackDuration').oninput=()=>{pushHistory();state.duration=T.MathUtils.clamp(Math.round(Number($('trackDuration').value)||300),1,30000);h.refreshMotion();setFrame(Math.min(state.frame,state.duration));changed();};$('trackZoom').oninput=()=>{$('timelineZoom').value=$('trackZoom').value;drawTimeline();};
 $('undo').before(Object.assign(document.createElement('button'),{id:'timelineAddKey',textContent:'＋关键帧',title:'当前通道插入关键帧（K / 双击轨道）'}),Object.assign(document.createElement('button'),{id:'timelineDeleteKey',textContent:'删除帧',title:'删除选中关键帧（Delete）'}));$('timelineAddKey').onclick=()=>$('addTrackKey').click();$('timelineDeleteKey').onclick=()=>$('deleteTrackKey').click();
 refresh();return {refresh,rows,choose,moved:()=>{commit();},open,clear,insert:()=>$('addTrackKey').click(),remove:()=>$('deleteTrackKey').click(),selected:()=>selection};
}
